### ISSUE TITLE
pagination error on mystock module 

### ISSUE THREAD

**Issue by selul** [Codeinwp/themeisle-companion#105]
@contactashish13 there are some issues with the pagination:
https://drive.google.com/file/d/1E16fVMLferKU9Vk7nbPxNkAVRUstgGXO/view

1) Loader is not visible when we reach the end of page ( when the 2nd page loaded ) , it should be an overlay over the current listed items, to give the users the feeling that something is loading.
2) The second page is loading more elements that it should, i dont know why. Also is adding duplicates.

Let me know if you have things clear.

**Comment by contactashish13** [comment]
@selul I've fixed the issue with the apparent duplicates. PR: https://github.com/Codeinwp/themeisle-companion/pull/110

Have assigned Rohit the CSS part and will follow up with him

**Comment by cristian-ungureanu** [comment]
@contactashish13 , works grate but we shouldn't make the ajax call if it's the last page. 
![gif](https://user-images.githubusercontent.com/9929553/32770666-1c3e6ae6-c929-11e7-8a60-cc63922689ba.gif)

**Comment by contactashish13** [comment]
@cristian-ungureanu can you please review it now?

**Comment by cristian-ungureanu** [comment]
It's working great now. Thanks!
