### ISSUE TITLE
improve ux on mystock module

### ISSUE THREAD

**Issue by selul** [Codeinwp/themeisle-companion#106]
@contactashish13 i would like to improve the ux for this module. 

For instance, when the user is on the mystock tab, the button for `Set as featured image` should turn into `Import and set as featured image` and the sidebar should no longer be present on click. 

Also, we will choose from flickr to import the `large image` size when they click set as featured image and import. 

When adding the image from media tab, we should display instead of `insert into post` -> `Import and insert into post`

Let me know if you have things clear.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/themeisle-companion/pull/143

**Comment by selul** [comment]
@contactashish13 all is working great, one small thing, when we insert the image from add media, the text shouldnt be `Download and set as featured image`, rather `Download and insert photo`

**Comment by contactashish13** [comment]
@selul have addressed this.

**Comment by rohittm** [comment]
I also found another bug with mystock import is that whenever an image is downloaded and used, It creates multiple of copies of same sizes in the Media library. here's the screenshot:

![mystock](https://user-images.githubusercontent.com/3204558/33605510-28794fe8-d9e0-11e7-90e6-ce575a4b36ac.JPG)

also it makes 'n' copies, where n increases by 1 on every download and insert of image!

**Comment by selul** [comment]
@contactashish13 can you try and check if you can replicate this ?

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/themeisle-companion/pull/150
