### ISSUE TITLE
improve the orbit fox dashboard

### ISSUE THREAD

**Issue by selul** [Codeinwp/themeisle-companion#107]
@bogdanpopa90 i would need your on on a long run project where we need to improve the orbit fox dashboard 

A raw skeleton would be like this: http://prntscr.com/h8ocz7 

Aspects of this new skeleton: 

1) The modules list will be on a sidebar in the right.
2) We will have a search form where we search thru modules.
3) In the middle area we will have module options, if available. 

The dashboard will need to be built on vuejs, this will be an opportunity for you to play around with this things.

Also the dashboard design will need to be similar with the WordPress admin dashboard, keep the same design patterns and guides.

**Comment by ineagu** [comment]
@selul I don;t think this is a priority for 2 reasons:

1. We have quite a bit of big issues on hestia that we need to solve first, hopefully 1 week is enough
2. We are not sure what the main direction will be here for orbitfox, it might become mainly a template directory on top of gutenberg or just the biggest selection of gutenberg addons, it depends on how things play out, so working on it might not help that much right now.

What do you think?

**Comment by selul** [comment]
@ineagu i've never said this is a priority, 

i've been talking with @bogdanpopa90  to spend some time on this when he get bored of the current work/tasks. 
i thought it will be a good idea to learn about vuejs too.

**Comment by ineagu** [comment]
ok, I agree. We can also try on wppr on some other plugin as well.

I was confused by this : https://www.dropbox.com/s/ihs1f3t1jiw3wxx/Screenshot%202017-11-10%2016.21.24.png?dl=0 . :D

**Comment by ineagu** [comment]
still generally giving more structure would help like : 

1. bogdanpreda makes a presentation on vue
2. bogdanpopa works for x days to finish this
3. writes a tutorial/video at the end and further present to others who are interested.

**Comment by selul** [comment]
@ineagu my bad, there is no backlog column.

**Comment by HardeepAsrani** [comment]
I'm personally really frustrated with the current Dashboard of Orbit Fox. Working with it seems not right. Also, the Raw sketch wasn't something good. Why don't we research into some existing Dashboards and see what can we make?

For example, here's how WordPress.com's Plugin dashboard looks:


![jul-01-2018 09-38-52](https://user-images.githubusercontent.com/2649903/42130953-9d3ffcac-7d12-11e8-95ac-8562d0f96384.gif)

This way we can group them by category, put a Configure button in the active modules, which can lead to a new page or just open a pop-up module for the settings, also a Search button probably.

Just an example, we can do some research and pick a great one. I really liked the one Jetpack had about 3-4 years back. It was easy but they changed it.

**Comment by HardeepAsrani** [comment]
Github unassigned Bogdon by itself, without me even scrolling up to that part of the screen.

**Comment by HardeepAsrani** [comment]
Another simple example is SiteOrigin's Widget Bundle. It's simple but the Card layout works for modules.
![screenshot-wide-eyed-oryx w6 poopy life-2018-07-01-09-52-12](https://user-images.githubusercontent.com/2649903/42130997-74d88e76-7d14-11e8-810a-3e10c3a621fe.png)

**Comment by selul** [comment]
closing stale issues.
