### ISSUE TITLE
Our focus widgets in Zerif Lite automatically removed on installing this plugin

### ISSUE THREAD

**Issue by kkashyap1707** [Codeinwp/themeisle-companion#11]
Hi Zerif Team,

Our focus widgets in Zerif Lite automatically removed on installing this plugin. Please have a look at it and provide the solution ASAP.

and Footer section icon(Google Map, Mobile and Social Icons) are also missing.

Please find the attached screenshot.
![our focus widgets in zerif lite automatically removed on installing this plugin](https://cloud.githubusercontent.com/assets/4715140/23642729/dded3b7c-0322-11e7-9fd5-81be0d320890.png)

![screenshot from 2017-03-07 10-47-45](https://cloud.githubusercontent.com/assets/4715140/23642839/e26b927e-0323-11e7-926b-a77e079971b3.png)

**Comment by rodica-andronache** [comment]
Hi @kkashyap1707,

Thank you for contacting us.
Do you have the plugin installed at this moment? Because I can see the Our focus widgets at this moments.
For the footer icons, can you please give me more details? Did you had the default icons that come with the theme? Have they disappeared when installing the plugin? Aren't you able to upload new icons?

Please let me know.
Regards,
Rodica

**Comment by kkashyap1707** [comment]
Hi @rodica-andronache 

Thanks for your reply.
Focus widget is working after reinstalling of the plugin.

The default icons that come with the theme is not displaying.

Please find the attached screenshot for reference.

![footer logos are missing](https://cloud.githubusercontent.com/assets/4715140/23690636/48477156-03e9-11e7-874b-7a5129de37a3.png)
![footer logo are displaying on backend](https://cloud.githubusercontent.com/assets/4715140/23690639/484aa93e-03e9-11e7-9e93-5219be9fda99.png)
![feature text is provided here](https://cloud.githubusercontent.com/assets/4715140/23690637/484834ec-03e9-11e7-8dcd-d4b323472ad7.png)
![feature text is missing](https://cloud.githubusercontent.com/assets/4715140/23690638/4849d1da-03e9-11e7-945a-6d5847bacc4a.png)

Waiting for your humble reply.

**Comment by rodica-andronache** [comment]
Hi @kkashyap1707 ,

I'm really sorry for the late reply. I somehow missed this message.

The default icons only appear if you are logged in. To be able to see them you need to actually save those options in the database. This can be done by uploading new images. If you want to use those icons, you can save them to your computer and then upload them in customize.
I know this is not very intuitive maybe, but we had to move the icons as sane defaults, and not show them unless the user is logged in, to work on wordpress.org repository rules.

Regards,
Rodica
