### ISSUE TITLE
Beaver Builder Widgets Research

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/themeisle-companion#111]
Take some time to research Builder Widgets. You should take a look at how others do this and redo the modules that were done for Elementor, in Beaver Builder.
I've outlined some steps that we should follow:

- [x] Take a look at other plugins that have Beaver Builder Widgets;
- [x] Learn how Beaver Builder Widgets are made;
- [x] Start Working on Widgets - mostly get acquainted to how they're made and integrated in Orbit Fox; 

**Some examples**: 
- https://wordpress.org/plugins/powerpack-addon-for-beaver-builder/
- https://wordpress.org/plugins/bb-bootstrap-cards/
- https://wordpress.org/plugins/ultimate-addons-for-beaver-builder-lite/

**Comment by ineagu** [comment]
don't be afraid to re-use gpl code from other tools :). also make sure they work well on beaver 2.0
