### ISSUE TITLE
add description + redo design using more native approach

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-companion#137]
https://www.dropbox.com/s/ka6cz55wxskirrm/Screenshot%202017-11-28%2021.47.28.png?dl=0

cc @abaicus

**Comment by ineagu** [comment]
What I mean by more native is bigger screenshots, search/categories + preview when click on screenshot . 

btw : https://www.dropbox.com/s/17ge28hzv55co06/Screenshot%202017-11-28%2021.49.54.png?dl=0

cc @rodica-andronache @selul

**Comment by ineagu** [comment]
@abaicus what I mean here is something like this : https://www.dropbox.com/s/v3ly0eeso44x7rl/Screenshot%202017-12-11%2020.24.04.png?dl=0, which mimim the theme browsing ux

**Comment by abaicus** [comment]
I don't know if it makes sense to add categories right now as we don't have that many templates.

**Comment by ineagu** [comment]
Sure, but we can still have the better layout with hover stuff, bigger images etc

**Comment by abaicus** [comment]
Yes. I'm going to take care of that. Was just saying that that particular feature (search) wouldn't be necessarily useful right now.
