### ISSUE TITLE
beaver/elementor /gutenberg form widget

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-companion#142]
One of the most common use case for such page templates are landing pages, going through this logic  landing pages need contact forms so we would need a form widget built-in our collection.

The free version will be quite simple, would let you to add a contact form, so you can have such a template : http://movingbox.ro , would let you embed a register widget, so you can have : https://unbounce.com/landing-page-template/harbor-business-services/ , it can be achieved by linking fields.

e.g : https://docs.elementor.com/article/92-forms

**Comment by selul** [comment]
@ineagu what the register widget will do ? Register a user into system ? What do you mean by linking fields? 

Will we be offering compatibility with pirate-forms ? 

Thanks !

**Comment by ineagu** [comment]
the widget should register a user into the system, like wp-register. By linking fields I mean that you can create such a form by linking 👎 

input1 -> user_name
input2->password
textarea3 
submit.

An alternative would be to simply choose : normal form/ registration form/ newsletter form .

pirate forms should be a different thing, this widget can maybe just pull default infos from pirateforms if it exist.

**Comment by selul** [comment]
i've made the specifications and assigned to andrei .
