### ISSUE TITLE
Form module

### ISSUE THREAD

**Issue by selul** [Codeinwp/themeisle-companion#147]
@andreilupu let's build an Orbit Fox module for forms integration. The intent is to create 3 types of Beaver/ Elementor/ Gutenberg widgets for 

- **Contact Form**
- **Newsletter Form** 
- **Registration Form**

### Contact Form

Fields: 
- [ ] Name  
- [ ] Email 
- [ ] Phone
- [ ] Message 
Each of those fields will have those 2 options :  
 - [ ] **Label** - textfield - the field label.
 - [ ] **Required** - select - which will have one of those 3 options - required | optional | hidden  
     - When someone select **required** the field will need to be filled in order to send the message. 
     - When someone select **optional** the field will dont need to be filled in order to send the message. 
     - When someone select **hidden** the field will hidden in the form. 

Beside those we will have two more options: 
 - [ ] Email - textfield - where the emails from the form will be sent.
 - [ ] Submit button label - Text label of the submit button.

### Newsletter Form

Fields:  
- [ ] Email  
- [ ] Submit button

With 1 option each :  
 - [ ] **Label** - textfield - the field label. 

Beside that we will have 3 more options:  
 - Subscribe to - select -  Mailchimp, Sendinblue - service where the emails will be subscribed. 
 - Access key  - text -  Mailchimp or Sendinblue access key.
 - List Id - text - the list id where to subscribe the user. 

### Registration Form

- [ ] Where on submit we will create an user in the system with the provided details.

Fields:  
- [ ] Email  
- [ ] Name
- [ ] Password
- [ ] Submit button

With 1 option each :  
 - [ ] **Label** - textfield - the field label. 

## General Requirements: 
- [ ] all the forms will include a honeypot mechanism to prevent spam. 
- [ ] i would recommend to build this as a composer library and the obfx module will instantiate that library. The reason of doing this is that we may reuse this in other plugins or as a standalone plugin. 
- [ ] As we talked we can generalize the widgets for all 3 page builders and control it from a single class that will handle the logic for each type of the form, i.e One OBFX_Registration_Form will handle the options and view for all 3 types of builders. 

CC @abaicus

**Comment by ineagu** [comment]
@selul I would recommend to check this out before : 

https://www.dropbox.com/s/o5tj34h02pvo1hq/Screenshot%202017-12-05%2010.47.50.png?dl=0
https://docs.elementor.com/article/92-forms

Another really good example is squarespace, is ideal in terms of UX : 

https://www.dropbox.com/s/6shrb0bo5t3nfwj/Screenshot%202017-12-05%2010.50.44.png?dl=0
https://www.dropbox.com/s/cduv2z6unr3k7bb/Screenshot%202017-12-05%2010.51.22.png?dl=0
https://www.dropbox.com/s/wi9kcqwfzmw1s41/Screenshot%202017-12-05%2010.52.13.png?dl=0
https://www.dropbox.com/s/jogx5wtc9ek52pr/Screenshot%202017-12-05%2010.52.21.png?dl=0

**Comment by selul** [comment]
@ineagu yes, i've been checking the elementor doc before, our forms will be more simple and will less options than those. I tried to incorporate only the most needed options for each type of forms. 

Thanks for pointing to the squarespace example !

**Comment by selul** [comment]
@andreilupu based our last call we will need to do those changes before release: 

1) for newsletter form adds error label and render the form also.
2) improve fields/form settings order, based on the type of the theme.
3) Check repeatable fields for beaver. 
4) Make username optional, user email as a username in case that username field is not.

**Comment by selul** [comment]
@andreilupu the style for content forms does not seem to be enqueued when loading the Elementor forms ( in the builder ). In the frontend, it seems to be loaded.

**Comment by abaicus** [comment]
I think the style can conditionally be enqueued in the construct of the function if you're in builder preview.

We have utility functions that check for that in Hesia - e.g: 

Elementor: 
https://github.com/Codeinwp/hestia-pro/blob/a4e81b26aa3cfdd2074bcd7531f94137687f4bda/inc/features/feature-pagebuilder-frontpage.php#L147-L159

Beaver:
https://github.com/Codeinwp/hestia-pro/blob/a4e81b26aa3cfdd2074bcd7531f94137687f4bda/inc/features/feature-pagebuilder-frontpage.php#L163-L175

**Comment by andreilupu** [comment]
I've made a PR which should fix this but I need your opinion on this https://github.com/Codeinwp/themeisle-content-forms/pull/15

The style was enqueued globally but the problem was that at the AJAX level, triggering a `wp_enqueu_style` was very late since the action `wp_enqueue_scripts` was already triggered. Sadly, there isn't an action which could help us there, maybe [elementor/element/{$element_name}/{$section_id}/before_section_start](https://github.com/pojome/elementor/blob/master/docs/content/hooks/php-hooks.md#elementorelementelementnamesection_idbefore_section_start) but our section id is very "dynamic".

Anyway, I do want that the old way of enqueuing the style in front-end to remain, so now I'm proposing that in the Elementor Editor, the widget should have its style inline. Being just for the editor I don't think it will be a problem.

**Comment by selul** [comment]
@andreilupu yes, looks ok for me

**Comment by rodica-andronache** [comment]
Not sure if here it's the place for this, but I got this warnings on the Newsletter form https://prnt.sc/i0rp0m

**Comment by selul** [comment]
i've added it in the repo for forms.
