### ISSUE TITLE
site setup/import

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-companion#151]
@selul the plugins is now great at importing page templates but we need to find a generic solution for importing full site templates aka demos.

How this will be different : 

1. collection of templates instead of template
2. can set a page as home, overriding user current settings
3. can change other theme settings including customizer
4. might require multiple plugins

so ideally it will need a basic wizard for it.

Another important mention is that site demos are tied to a theme for now due to the fact that we cannot really change the header/footer of all themes consistently, thinking about this, the wizard part can be in the theme as well ( keeping w.org rules ).

I would try to detail in a further issue why we need that.

**Comment by selul** [comment]
closing for #152
