### ISSUE TITLE
change description

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-companion#168]
@selul @abaicus we should update this : https://www.dropbox.com/s/u80ec24f6rofose/Screenshot%202017-12-27%2015.03.59.png?dl=0

**Comment by selul** [comment]
@ineagu what we should outline there ? The features that OrbitFox provides ?

**Comment by ineagu** [comment]
we can have this done after we brainstorm right? What day works for you next week?

**Comment by ineagu** [comment]
@s2abina We are looking for a 148  characters description for the plugin, so potential users can easily get what this is about, this will show in plugins search and wp-admin/plugins.

Current one: Enhance your website with extra functionality through modules like: social media share buttons & icons, reporting, analytics(upcoming), security(u …

JetPack: The one plugin you need for stats, related posts, search engine optimization, social sharing, protection, backups, speed, and email list management.

OrbitFox is aiming to be a wp enhancement tool, for now, it provide users with 👍 
-> menu icons module
-> sharing icons module
-> Template Library (Free Collection of landing page templates that works with ANY theme)
-> Builders Blocks ( Blocks that works with major page-builders, for now with Elementor, Beaver Builder)  ** need help with module name
-> Extra front-page sections for Hestia/Zerif

Soon:
->  Full-width page template module (useful for page builders)

**Comment by s2abina** [comment]
Only saw this now.

@ineagu @selul how do you like this description (147 characters):

This swiss-knife plugin comes with a quality template library, menu/sharing icons modules, and newly added Elementor/BeaverBuilder page builder widgets on each release.

**Comment by s2abina** [comment]
@ineagu @selul For a less technical description we could go with the one below, inspired by @dascalescuro's copy:

>This swiss-knife plugin extends your website functionalities with modules that work for any theme and adds new page builder widgets to Elementor and Beaver Builder.

**Comment by ineagu** [comment]
not convinced about either. for this iteration we can go with : 

This swiss-knife plugin comes with a quality template library, menu/sharing icons modules, and newly added Elementor/BeaverBuilder page builder widgets on each release. as php description/readme description @selul
