### ISSUE TITLE
add branding to menu icons

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-companion#169]
@selul the menu icons feature while is cool is not clear how it arrived there and what plugin takes care of that, we can easily fix this by adding a bottom bar to this window mentioning something like : Powered by OrbitFox : https://www.dropbox.com/s/st6c8pys1oxjs29/Screenshot%202017-12-27%2016.42.46.png?dl=0 .

**Comment by selul** [comment]
sounds like a good plan. 

@contactashish13 can we add a footer in that area, with `Powered by OrbitFox` text.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/themeisle-companion/pull/173

**Comment by selul** [comment]
nice turnaround. Well done !
