### ISSUE TITLE
Builder Blocks module

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-companion#177]
@selul as we discussed we should merge all builder modules under a single module, which is automatically loaded if the corresponding builder is present.

**Comment by selul** [comment]
@andreilupu related to content forms, can we do the next thing.

* Load the elementor forms right in the elementor module in obfx.
* Load the beaver forms right in the beaver module in obfx.
* Remove the current content forms module.

**Comment by andreilupu** [comment]
this was fixed in 5fbd0e1a103bfd552f52e6d29299027751527d70
