### ISSUE TITLE
next non-builder module

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-companion#178]
@selul based on our talk today we should probably start working on a non-builder popular module, from a business perspective few candidates are : 

1. security (basic security practices)
2. Caching
3. Downtime monitoring
4. Google Analytics integration

**Comment by selul** [comment]
@ineagu, I would go with a downtime monitoring first? A very simple version when they subscribe to the downtime monitor using their mail, from the orbit fox dashboard. What do you think?

**Comment by ineagu** [comment]
@selul I was doing some research here and looks like the most interesting one to pursue is : Google Analytics integration. However for such modules we have a new use-case that is not clear right now, what should we do when there are already installed more powerful solution?
I will open separate issues
