### ISSUE TITLE
Dashicons font is not enqueued on front-end [Menu Icons Module]

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/themeisle-companion#186]
Even though you're able to select Dashicons as menu icons, they're not enqueued on the front end, so they're only visible to the logged in users.

cc: @contactashish13 @selul

**Comment by contactashish13** [comment]
@abaicus Have fixed this. PR: https://github.com/Codeinwp/themeisle-companion/pull/190

**Comment by abaicus** [comment]
@contactashish13 Thanks for the help! 👍
