### ISSUE TITLE
Integrate Shop Isle Companion in the plugin.

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/themeisle-companion#19]
Add the features from the shop-isle-companion to this companion so we can distribute on wporg. 

We should try migrating users from shop-isle-companion to this one by stopping the updates for that companion. There are multiple routes of doing this: 
1. Add a notice to customizer to install ti-companion and one to remove shop-isle-companion.
2. Stop updates for shop-isle-companion and link to the themeisle companion on our website. 

- [ ] After this is done, support team should be informed how to guide Shop Isle users.

cc: @ineagu @rodica-andronache

**Comment by ineagu** [comment]
can't we just ignore the  shopisle companion code once ti-comp is installed? even if the user didn't uninstall the 1st?

**Comment by abaicus** [comment]
Sure we can

**Comment by ineagu** [comment]
@abaicus is this hard to do? we can migrate both azera/shopsile to obfx while making shopisle about template as an elementor one.

I mean how long will take to develop?

**Comment by abaicus** [comment]
Not really that hard. But I don't really think that we should remove the current about page template that goes with the companion. 

I think this is a one-two day job to bring all in the companion-legacy module without breaking anything.

**Comment by ineagu** [comment]
not remove the existing one, but we can create one as well in elementor

**Comment by stefan-cotitosu** [comment]
@abaicus Can we close this?

**Comment by abaicus** [comment]
Sure!
