### ISSUE TITLE
Customizer importer exporter module

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/themeisle-companion#199]
Customizer importer exporter module:
- Add to orbit fox companion;
- Copy - paste don’t spend much time but try removing useless parts;
- Only show when user has hestia / zerif like the legacy module;
- We should still be able to call the importer programatically;
- Make sure that this works when both OBFX and the Customizer Export Import plugins are installed and activated; 

We're going to try adding the simplified functionality from the Customizer Import Export plugin: https://wordpress.org/plugins/customizer-export-import.

**Comment by rodica-andronache** [comment]
@abaicus is this still to do? :D

**Comment by abaicus** [comment]
I don't think so @rodica-andronache. 👍
