### ISSUE TITLE
Notice

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#221]
I got this notice in the OBFX dashboard:  Notice: Undefined index: link-id in C:\wamp\www\wordpress\wp-content\plugins\themeisle-companion\core\app\helpers\class-orbit-fox-render-helper.php on line 377

https://prnt.sc/ioxgin

https://prnt.sc/ioxgp9

**Comment by rodica-andronache** [comment]
I got some other notices too when using Gutenberg https://prnt.sc/jkpn2w

**Comment by contactashish13** [comment]
@rodica-andronache I believe this is fixed. Can you please confirm?

**Comment by rodica-andronache** [comment]
yes, seems fine :)
