### ISSUE TITLE
[new module] script manager (add tracking to website)

### ISSUE THREAD

**Issue by dascalescuro** [Codeinwp/themeisle-companion#226]
This goes well with the GA tracking and Template Directory modules, I think...

Users need adding scripts like the Facebook pixel, Google tag manager, Hotjar etc etc.
The best way is to add them via a plugin.
A script manager module that can add, remove, edit and toggle your scripts might help users that create landing pages with Template Directory.

Suggested locations in the page's code where the scripts should be inserted:
- before </head>
- after <body>
- before </body>
This can also be used for CSS changes...

Not sure if an option to load the script sitewide or just on specific pages would help...

Here is an plugin example: https://wordpress.org/plugins/header-and-footer-scripts/

CC: @ineagu @abaicus

**Comment by cristian-ungureanu** [comment]
This module was implemented but we forgot to close the issue.
