### ISSUE TITLE
[Menu Icons] Custom navwalker overwrites others.

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/themeisle-companion#227]
There is a problem with the "Menu Icon" feature, when it is enabled in Orbit Fox, the default theme menu settings for OceanWP are not present, it needs to be solved, otherwise, users would not be able to create mega menu, so if this feature is enabled, the default menu settings needs to be present.

Do you have any ideas here @contactashish13? From what I gather, we're extending `Walker_Nav_Menu_Edit` class and using our own. OceanWP also does that. Is there any chance to make them work together? :D

**Comment by contactashish13** [comment]
@abaicus I've installed OceanWP and I'm not sure which settings you are referring to. Can you please list down the steps/screenshots to reproduce this issue?

**Comment by abaicus** [comment]
@contactashish13 The menu item settings for OceanWP mega menu. You can install OceanWP theme. If you disable our menu icons module, their settings become available.

![image](https://user-images.githubusercontent.com/15010186/37961543-43883e96-31c1-11e8-9e46-39fdf5a87ac4.png)

**Comment by contactashish13** [comment]
@abaicus I don't think both can work together. It appears this is a very old problem with WP: https://core.trac.wordpress.org/ticket/27280

**Comment by ineagu** [comment]
this doesn't look good :D So you see now work-around for this? I suppose we should disable the functionality for this theme?

**Comment by contactashish13** [comment]
@ineagu I suppose that's the safest way to go about it. I've made changes so that if a custom walker exists, we bail.

@selul PR: https://github.com/Codeinwp/themeisle-companion/pull/229

**Comment by ineagu** [comment]
@abaicus should we be maybe more specific here? https://wordpress.org/support/topic/icons-conflict-with-oceanwp-theme/. Like if activated it disables oceanwp megamenu functionality?

**Comment by abaicus** [comment]
It shouldn’t disable it anymore. The icons don’t work unfortunately.

**Comment by ineagu** [comment]
I was talking about the notice :D

**Comment by abaicus** [comment]
Got it. I guess we should be more explicit.
