### ISSUE TITLE
Dismiss notice issue

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/themeisle-companion#233]
It takes you to an empty page when you click on X. The issue is dismissed after clicking back and refresh page

![gif](https://user-images.githubusercontent.com/9929553/38243391-09314e34-3740-11e8-95ca-24cc24c6cd27.gif)

**Comment by rodica-andronache** [comment]
+1  
it depends on which page you are in the admin area. for me, it's not working from the PirateForms settings page admin.php?page=pirateforms-admin

**Comment by contactashish13** [comment]
@cristian-ungureanu I'm unable to replicate it with the latest version. Is this still an issue?
