### ISSUE TITLE
Zerif to _Blank [Front Page to Builder]

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/themeisle-companion#239]
Create a flow to notify users with Zerif about _Blank. After activation, programatic move the front page content to a builder template. Dinamically create the JSON and import it in the front page content.

**Comment by contactashish13** [comment]
@abaicus is this still required? If so, can you please mention the intent behind this?

**Comment by abaicus** [comment]
@contactashish13 This has been done in a way in themes. I'm not sure if we still want to add it to OBFX too. 

cc @rodica-andronache @ineagu

**Comment by ineagu** [comment]
I guess we are fine now.
