### ISSUE TITLE
Portfolio CPT Module

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/themeisle-companion#240]
Right now we recommend Jetpack in our themes. We can do this in OrbitFox with an `add_theme_support('obfx_portfolio')`. 

ref: https://wordpress.org/support/topic/request-to-extend-the-plugin/

PS: Maybe we can even add some display options in the future if we plan on extending it - so it wouldn't necessarily be tied to our themes.

**Comment by contactashish13** [comment]
@abaicus can you provide more details about this, if this is still required?
