### ISSUE TITLE
Hestia Very Top Bar flipped

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/themeisle-companion#262]
In Hestia Lite there is a very top bar which has a menu location and a widgets area. There is no option to choose what to be on the left and what to be on the right side of the VTB in the lite version.

By default, menu location was on the left side and the widget area on the right side.
When you upgrade Orbit Fox from 2.4.6 to 2.4.7 the items are flipped in the VTB.
The menu is moved to the right and the widgets to the left. Some users are not happy with this change, as they don't have a layout option in Hestia Lite.

<img width="1056" alt="vtb" src="https://user-images.githubusercontent.com/26867648/41972256-f9ea45c6-7a19-11e8-9930-5c948960cf2e.png">

Please put them back.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu but what happened here?  :D Is this supposed to be fixed in obfx?. 
In the lite version of hestia, we have the layout as menu -> widgets, and in pro we have the default value as widgets -> menu? Is this ok?
