### ISSUE TITLE
New features showcase.

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/themeisle-companion#266]
Redo wp.org banner Include `Safe updates` & `CDN`.

Maybe edit the OrbitFox video to include more details on these two features? cc: @ineagu

**Comment by ineagu** [comment]
@selul I think is best to update people one obfx change of plans moving forward 🗡 

In short : 

1. Image optim+ cdn will live under a separate brand, the obfx module will be just a way to integrate "imigi" into wp.
2. Safe updates for short/medium term can stay as it is in obfx, later on we'll launch a  "safe-update & monitoring" service
3. So no dashboard & obfx pro for now.

Feel free to change the banner however for safe updates/cookie notice.

**Comment by cristian-ungureanu** [comment]
I will close this issue, seems like we forgot to close it.
