### ISSUE TITLE
[Mobile] Cookie notification is behind the sharing icons

### ISSUE THREAD

**Issue by FitzChris** [Codeinwp/themeisle-companion#283]
From a user reported on Facebook.

can you please update the following css in your orbit fox plugin
.obfx-cookie-bar {
	z-index: 10000 !important;
}
when viewing on mobile device with sharing icons displayed at the bottom, the cookie notification is behind the sharing icons

**Comment by radu-themeisle** [comment]
I think this issue was solved in the meatime 🙂: http://prntscr.com/lu2rrx
