### ISSUE TITLE
[Downtime Notifying] Still sending emails after stopped using plugin

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/themeisle-companion#286]
A user reported he's still getting emails of downtime after he deactivated the plugin, so we should unregister when they deactivate. Also, there's no option to disable the feature as well.

**Comment by selul** [comment]
@ineagu thanks for follow-up.

@HardeepAsrani for now if they want to disable this, they need to disable the module.
I think what we can do very effectively is to include in each email to stop the uptime check. 
Will you be interested in doing this?

**Comment by HardeepAsrani** [comment]
Fixed in http://github.com/Codeinwp/monitor-obfx
