### ISSUE TITLE
Orbit Fox not letting me publish updates

### ISSUE THREAD

**Issue by Jordz2203** [Codeinwp/themeisle-companion#288]
Hi guys, Im trying to publish an update to my website but I cannot do so with orbit fox activated. I usually deactivate it to make changes but now I need to change an orbit fox page with icons so I cannot. I use Fagri theme

**Comment by Jordz2203** [comment]
Fixed Orbit Fox and Elementor clash

**Comment by selul** [comment]
Hello @Jordz2203

Sorry for such late notice, we had some issues with the Full-Width template in case that you were using it. I hope this latest version fixes your issue. Otherwise, feel free to re-open the issue.
