### ISSUE TITLE
Replace 'Sizzify' mention with 'OrbitFox' 

### ISSUE THREAD

**Issue by sab2ina** [Codeinwp/themeisle-companion#294]
In the Template Directory http://prntscr.com/l4bu2r we should change 'Sizzify' to 'OrbitFox'

**Comment by contactashish13** [comment]
@sab2ina can you check if you are using the updated version?

![image](https://user-images.githubusercontent.com/12953439/46944168-048c3b80-d08f-11e8-8091-7c76913c83d0.png)

**Comment by contactashish13** [comment]
@sab2ina can we close this if this is no longer an issue?
