### ISSUE TITLE
Font Awesome 5 support

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/themeisle-companion#295]
Given that we already have added Font Awesome 5 to Gutenberg Blocks, we should also add its support to Menu Icons module. I tried doing it in my free time and was successful in doing so.

It works and all, just we have to think of backward compatibility, for which there are two ways of doing it:

1. Just use Font Awesome 5, and run a migration which will replace already saved menu with the new FA prefixes.

2. Just let the old ones go and add a shim of FA4 so that old ones also work, which we can also do because Gutenberg is already enqueuing shim + theme or something else might be using FA4 so it's a better idea.

What do you think? @abaicus

**Comment by radu-themeisle** [comment]
@HardeepAsrani we made huge progress with adding FA5 to Hestia and we can use the second solution of using the shim of FA4 which is already in Gutenberg modules as it's the best one.
I think we should work on a solution to use FA5 from a single place in OBFX for all the modules.

**Comment by HardeepAsrani** [comment]
@radu-themeisle Sure, we can do that. How should we progress? Should I send a PR?

**Comment by radu-themeisle** [comment]
@HardeepAsrani yes 🙂

**Comment by radu-themeisle** [comment]
No, just @HardeepAsrani to check out cases where FA5 form Otter Blocks (integrated in OBFX) breaks icons that use FontAwesome font-family.
An example was the map-marker icon in th "Contact Us template" from Templates Directory. It didn't render the icon due to FA5 having priority and Elementor setting specifically the font-family for the icon widget.

**Comment by HardeepAsrani** [comment]
Is it still a thing @abaicus?

**Comment by abaicus** [comment]
It's been two years, so I don't think. :smile:
