### ISSUE TITLE
Notices when using Beaver Themer

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#297]
Notice: Use of undefined constant THEMEISLE_COMPANION_VERSION - assumed 'THEMEISLE_COMPANION_VERSION' in C:\wamp64\www\wordpress\wp-content\plugins\themeisle-companion\obfx_modules\beaver-widgets\custom-fields\number-field\number_field.php on line 27

**Comment by cristian-ungureanu** [comment]
This issue is not present anymore.  I'm closing this.
