### ISSUE TITLE
Security bug reported by an user.

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/themeisle-companion#303]
ticket link -> https://secure.helpscout.net/conversation/703895490/173175?folderId=212385
### He described the following scenario:

If the Elementor plugin is also installed then the 
'wp-json/templates-directory/import_elementor' endpoint allows an 
unauthenticated user to import files. Due to a flaw with Elementor this 
can allow for uploading arbitrary files and unless the server is 
explicitly setup to deny it then arbitrary PHP code can be executed.

All that is required for this attack is the themeisle-companion plugin 
to be installed along side the Elementor plugin. If these conditions 
are met than an unauthenticated user can upload and execute arbitrary 
code resulting in complete system compromise.

**Comment by selul** [comment]
@abaicus what do you think ?

**Comment by abaicus** [comment]
The rest route doesn't have a capability callback. I'm going to send a PR asap fixing this and release both Sizzify and OBFX. Thanks for letting us know!

**Comment by selul** [comment]
⚔️

**Comment by abaicus** [comment]
👍 fixed.
