### ISSUE TITLE
Cookie message "Agree" button 

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/themeisle-companion#304]
@contactashish13  I think will be helpful if we can add a button from where the Text Agree of the cookie can be modified and wrote something like "Accept". 

A button similar to "Policy Button Label" where you can edit the "View Policy" with what you want.

**Comment by contactashish13** [comment]
@mileamadalin can you explain the behavior in more detail, possibly with example screenshots?

**Comment by mileamadalin** [comment]
@contactashish13 Sure. I have attached some images: 

https://www.dropbox.com/s/3wtmx7e34av2cml/Screenshot%202018-11-19%2022.43.17.png?dl=0

https://www.dropbox.com/s/gbnjvl92aocrjlk/Screenshot%202018-11-19%2022.46.16.png?dl=0

**Comment by contactashish13** [comment]
@mileamadalin perfect, thanks!

PR: https://github.com/Codeinwp/themeisle-companion/pull/306
