### ISSUE TITLE
FA5 Menu Icons

### ISSUE THREAD

**Issue by radu-themeisle** [Codeinwp/themeisle-companion#323]
We should implement FA5 in the Menu Icons module because if you use Hestia and a brand icon (e.g. Facebook) in the menu it will not show because it requires the "Font Awesome 5 Brands" font-family. Right now because of the v4.7 class, the brand icons are converted to Font Awesome 5 Free instead of Brands.
The tricky part is making sure that by implementing FA5 classes we don't break sites of users that don't use Hestia and use OBFX with another theme.

**Comment by ineagu** [comment]
that should not be the case I guess Radu, menu icons module come with proper font awsome 4,7 right? the module should work on all themes, no matter if they are on 4,5 or no fontawesome.

If isn't working on hestia it means we did something wrong there and how we are breaking orbitfox we would break all other plugins using hestia and FA 4.7, right?

I haven't checked anything technically, but logically this isn't right.

cc @rodica-andronache

**Comment by ineagu** [comment]
not sure in the same way, woocommerece integration is broken or WPPR or other plugins using FA4, like our menu icons plugin.

**Comment by ineagu** [comment]
or @abaicus probably can help on this, probably you got into this cause you applied FA 5 on navbar, which probably we shouldn't in the first place, but use svg for search+cart icon, in this way we can avoid for e.g loading FA on internal pages since there are no other icons, we can load on all only when user is using them in very top bar and this is active, or something like this.

dashicons are for e.g included in every wp install, we can use that too, without collision for cart/search, we can't load fontawesome on all site just for a search icon :D i think

**Comment by abaicus** [comment]
@Codeinwp/theme-dev 

I think we should drop the shim and not force FA5 loading. Best thing we can do is add an option in pro, or make a simple plugin that would do this:

- Dequeue current (4.7) version;
- Enqueue new version (5);
- Filter the HTML template we're showing in the IconPicker; 
- Filter the classes in the theme so they'll be displayed in fa-5 where that's the case (e.g. search icon, cart icon, account page);
- Add inline styles if necessary; 

I don't think it's ideal what we're doing now as it's not a voluntary choice for the users and it can and **will** break plugins - we're already seeing that with OrbitFox Menu Icons module. 

It seems there's a reason why nobody updated to FA5 until now. I'd also advise to stray away from their icons as much as we can in the future if we're building features for the users. 

For example there are sites that are loading 4 .css files just for font-awesome right now + the shim.
https://sprayfoamsupply.com/

![image](https://user-images.githubusercontent.com/15010186/49864406-0eba8400-fe0b-11e8-8071-08845729f088.png)
  
Also the footer icons are essentially broken. 

![image](https://user-images.githubusercontent.com/15010186/49864442-27c33500-fe0b-11e8-8ca4-96ed8de0070a.png)

**Comment by abaicus** [comment]
@radu-themeisle @ineagu I'm going to close this as I've finished reverting everything back how it previously was. 

I think maybe we should take a look at how to implement this in a small plugin or in the pro version?
