### ISSUE TITLE
Load fontawesome in all pages issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/themeisle-companion#324]
A customer recommended us to only load the font awesome only where is necessary

http://prntscr.com/lqjedm
http://prntscr.com/lqjem1

ticket URL: https://wordpress.org/support/topic/load-fontawesome-in-all-pages/

**Comment by ineagu** [comment]
there seems to be some FA issues indeed : https://wordpress.org/support/topic/fa-awesome-icons/ 

cc @contactashish13

**Comment by contactashish13** [comment]
@mileamadalin I can't seem to reproduce this. I have orbit fox and hestia installed and I have enabled menu icons in orbit fox and I can still see the icons in the menu.

![image](https://user-images.githubusercontent.com/12953439/53316031-38ecef80-38ec-11e9-87e9-f556e1c034a1.png)

**Comment by mileamadalin** [comment]
@contactashish13 For me as well is working with WordPress 5.1, Hestia Version: 2.2.1 and Orbit Fox Version 2.7.5 

![screenshot 2019-02-25 at 08 52 17](https://user-images.githubusercontent.com/6906834/53319250-b576d280-38da-11e9-8622-f827f433ed91.png)
