### ISSUE TITLE
Post Grid – Excerpts?

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/themeisle-companion#329]
We have a customer that asks for excerpt instead of the full post. I think that's a good idea.

"Is it possible to add an option to use the first xxx words of the excerpt rather than the full post?"

Ticket link: https://wordpress.org/support/topic/post-grid-excerpts/

**Comment by rodica-andronache** [comment]
@mileamadalin as far I saw, I think we already have this in the plugin
