### ISSUE TITLE
Form module ~required field issues

### ISSUE THREAD

**Issue by web1o1** [Codeinwp/themeisle-companion#338]
Hi there.. just found this issue.. 
while editing "Contact Form" within elementor..

if the " Message field" is deleted..or the "Required" section is set to 'NO',..  the form, once published will spit out a 'Missing message' error and stop the form from being sent.
.. anyway to configure straight from the Page Builder?
curious

**Comment by SilviuDinu** [comment]
@contactashish13 a user with Neve Doctors also reported this to us. The Contact Form widget added by Orbit Fox is a bit faulty (can't detect field input).

Here is a video of the issue -> https://embed.vidyard.com/share/aLsTL2WRvoDp2EbfM1oX5Y

**Comment by cristian-ungureanu** [comment]
@selul I've managed to find and fix the problem but I think we should improve the functionalities of this module. Maybe we can make a plan for it on Monday.
