### ISSUE TITLE
[Social Sharing Module] Remove Google+

### ISSUE THREAD

**Issue by radu-themeisle** [Codeinwp/themeisle-companion#351]
According to this [article](https://www.theguardian.com/technology/2019/feb/01/closure-google-plus-everything-you-need-to-know) on April 2nd Google+ has been discontinued so we should remove this option form the Social Sharing Module.

**Comment by cristian-ungureanu** [comment]
The icon was removed in [this PR](https://github.com/Codeinwp/themeisle-companion/pull/561)
