### ISSUE TITLE
[General] Text-background color contrast ratio

### ISSUE THREAD

**Issue by radu-themeisle** [Codeinwp/themeisle-companion#352]
The settings could benefit from an improved color contrast ratio, right now the colors make the text very hard to read: http://prntscr.com/nfn365

- For the **title** I propose this color:
#3B49AF (WCAG AAA compliant)
- For the **subtitle** I propose this color:
#50595E (WCAG AAA compliant)

Also, we should use a font size of 14px for paragraphs and 16px  + a font weight of 600 for titles.

This would be the result: http://prntscr.com/nfn31g

**Comment by cristian-ungureanu** [comment]
Seems that this was merged but we forgot to close the issue.
