### ISSUE TITLE
Menu icon module conflicts with Advanced Custom field

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/themeisle-companion#360]
@HardeepAsrani 

When I use orbit fox plugin with Advanced custom field plugin and activate the menu icon module it shows a message "There appears to be a conflict with the plugin advanced-custom-fields. This module may not work as expected." 
Screenshot: http://prntscr.com/o4tb7j

I tried the menu icon plugin and it's working fine with ACF.

**Comment by HardeepAsrani** [comment]
cc @abaicus

**Comment by irinelenache** [comment]
Tested this and it works fine, no messages 👍
