### ISSUE TITLE
MyStock module issue

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/themeisle-companion#366]
@contactashish13 looks like the module MyStock Import is not working as expected. When I'm trying to import an image to add it on a post or page, the old box is not appearing anymore. 

Please see the video attached: https://www.dropbox.com/s/qr7qvtzuict61yq/Screen%20Recording%202019-07-18%20at%2016.31.25.mov?dl=0

**Comment by contactashish13** [comment]
@mileamadalin is this a problem with only the block editor or also the classic editor?

**Comment by cristian-ungureanu** [comment]
The module works only when gutenberg si not enabled. I've tested it a while
ago and it works fine. You can close this issue.
