### ISSUE TITLE
add notifications to hestia/zerif notification system

### ISSUE THREAD

**Issue by abaicus** [Codeinwp/themeisle-companion#37]
If our about class is present, hook a notification for people to :

Install elementor if neither beaver/elementor is installed. ( 12 hours after theme get activated )
In case beaver/elementor are installed, add a notification and inform people about our templates ( about page for now ), that will be presented in orbitfox.
cc @abaicus see with @preda-bogdan if he can help or the "themes" team can do it. Maybe at least a skeleton for the templates part can be useful. see oceanwp importer example.

**Comment by selul** [comment]
closing stale issues.
