### ISSUE TITLE
Speed improvements for Starter Sites

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#370]
This is just a starting point. The goal is to make sure OBFX is working well and doesn't have any negative impact on the Starter Sites and the theme.

For start, you can go through all of Neve's Starter Sites and identify which modules of OBFX are used or not for each one of them.

We'll want to make sure we activate just the modules needed for each specific Starter Site in the onboarding and load just the CSS and JS files needed for each module.

There is this PR https://github.com/Codeinwp/themeisle-companion/pull/365 where Ash added a filter that can be used to filter the activated modules. We need to find a way of using that to filter the modules.

Another thing would be the one related to FA5, that's loading in Otter https://github.com/Codeinwp/hestia-pro/issues/2110

cc @selul

**Comment by selul** [comment]
Some things that we need to care here: 

- [ ] Audit each OrbitFox module and make sure we load the JS/CSS files only when needed. 
- [ ] Js files should always be loaded in the footer. 
- [ ] For starter sites, make sure to have active, after import, only the modules from OrbitFox that are needed. Each starter site might have on the import file an option which should explicitly tell which module to load.  
- [ ] Investigate the current issue that we have with Otter, is the shim file a fix for it?

**Comment by rodica-andronache** [comment]
- The FA icons don't load in the Star Rating component in Elementor, when you are not logged in on the demo. It might be related to OBFX https://github.com/Codeinwp/ti-starter-sites/issues/1

**Comment by selul** [comment]
@cristian-ungureanu during the audit that you conduct, you might have this in mind also: 

https://github.com/Codeinwp/themes-internal/issues/49

**Comment by cristian-ungureanu** [comment]
For OrbitFox modules:

**Social Sharing Module** - allow admin files to load only on the obfx config page and the public scripts to load only on posts and pages. Also, load js files in the footer.

**Gutenberg Blocks** - OK

**Uptime Monitor** - OK

The **Analytics Integration** module was loading an admin js file outside of its config page. Now it's fixed and the script loads in the footer.

In **Page builder widgets** module the files are loading only when rendering the widgets so it's ok. I've fixed some issues with forms giving the error "Object Object". This happened when the Rest API was disabled for unauthenticated users. Fixed it here https://github.com/Codeinwp/themeisle-content-forms/pull/41

The **Template Directory** module contains a function that is not used anywhere in **template-directory/init.php** file. The function is called **enqueue_template_dir_scripts** and it's a public function, the same function from templates-directory composer module. I don't know if it's used by another plugin or was forgotten there.

**Menu Icons** module was loading font awesome 4.7 even if the icons weren't used. Now checks any active menu and it loads fa4 when is needed

**MyStock Import** - the module couldn't fetch photos, added a fix. It only works on the classic editor. Would be nice to have it working with Gutenberg too ( maybe a custom block )

**Policy Notice** - OK

**Safe Updates** - OK

**Comment by selul** [comment]
All looks good, it seems the build here is failing https://github.com/Codeinwp/themeisle-companion/pull/372 due to PHPUnit tests. can you have a look ?

**Comment by cristian-ungureanu** [comment]
Fixed it, thanks @selul. 
I've updated Hestia's starter sites too: https://github.com/Codeinwp/hestia-pro/pull/2131 and checked the icon problem with Otter. After the migration that @abaicus made, everything works fine.

I think someone should also check the starter sites on Hestia too, they don't look that well.
