### ISSUE TITLE
Invalid argument supplied for foreach() in menu-icons/init.php

### ISSUE THREAD

**Issue by viennaa** [Codeinwp/themeisle-companion#377]
**Preamble**
What version of Orbit Fox are you using?
2.8.6
What version of WordPress are you using are you using?
5.2.2
What did you do?
Upgrade from Orbit Fox 2.8.5 to 2.8.6
What did you expect to see?
No warnings and everything working as usual
What did you see instead?
4 times  `Warning: Invalid argument supplied for foreach() in /www/htdocs/w00dc2cd/fotoclub-kontrast.de/wp-content/plugins/themeisle-companion/obfx_modules/menu-icons/init.php on line 126`

**Details**
When hitting the startpage of my website I am getting greeted by:

` Warning: Invalid argument supplied for foreach() in /www/htdocs/w00dc2cd/fotoclub-kontrast.de/wp-content/plugins/themeisle-companion/obfx_modules/menu-icons/init.php on line 126`

Same behaviour other users are describing here: 
https://wordpress.org/support/topic/error-after-updating-to-2-8-6/

I guess this function is not returning properly and it should be checked before iterating over it. Not sure though, just trying to be helpful:
https://github.com/Codeinwp/themeisle-companion/blob/master/obfx_modules/menu-icons/init.php#L125

**Comment by selul** [comment]
@viennaa this should be fixed in the latest release of 2.8.7.

Thanks a lot for reporting.
