### ISSUE TITLE
MyStock module not working in Gutenberg

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/themeisle-companion#386]
When editing a post in Gutenberg, if I want to add an image block, there is no mystock tab next to the media library([screenshot here](https://prnt.sc/pav642)).

If I use the [Classic Editor plugin](https://wordpress.org/plugins/classic-editor/), it works.

Also, it doesn't work in Elementor with the image widget, not sure if it's supposed to work there.

**Comment by stefan-cotitosu** [comment]
https://secure.helpscout.net/conversation/964729589/202692/

**Comment by cristian-ungureanu** [comment]
Don't know if we can fix this, a quick fix is to hide the module if gutenberg is active

**Comment by rodica-andronache** [comment]
just as a reference we also got a bad review about this https://wordpress.org/support/topic/uhm-ok/
