### ISSUE TITLE
"Missing Company" Error in Contact Form.

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/themeisle-companion#387]
I tested this in Hestia and here are the results:

1. I added a field and named it "Company" by clicking the duplicate icon on the existing default items.
It shows on the Contact form and was able to send the message. https://snipboard.io/D4Ebt7.jpg

2. I added a field and named it "Company" by clicking the Add Item button.
It shows on the Contact form but was not able to send because of the 'Missing Company' message.
I change the Type from text to text area and got the same issue. https://snipboard.io/Y7fovR.jpg

I did not receive an email on both tests.

**Comment by purplecodes** [comment]
Additional note:
As tested by the user, he was able to receive his contact form submitted on his site on his email when testing #1 (as above). The company field can be seen on the frontpage's contact form and the message has been sent but on the email, the company field is not visible.

https://secure.helpscout.net/conversation/967270141/202982/

**Comment by cristian-ungureanu** [comment]
This was fixed in this PR https://github.com/Codeinwp/themeisle-content-forms/pull/45
