### ISSUE TITLE
[Post Type Grid] Remove default box shadow on images

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#390]
By default, images have a box-shadow, even though the `Box shadow option` is empty.

To keep things the same on update, we could change the default value of the Box shadow option to match the default box shadow.
Or if we don't care about that, just remove the default box shadow.

![Screenshot (3)](https://user-images.githubusercontent.com/3266155/68295842-efb88680-009b-11ea-98b0-b0e004e63e7b.png)

Source: https://www.notion.so/themeisle/19423b64733743389c90461fe9893ceb?v=c62fbb45fc9c4746b2e4671d6b6ceeb4&p=09842fb54af544629ce1e810c277978c

**Comment by cristian-ungureanu** [comment]
@selul @rodica-andronache that kind of control does not accept any default data [ https://github.com/elementor/elementor/issues/5920 ]. There are only two options, either we remove the default CSS ( but then any site that didn't have the image box-shadow modified in Elementor won't have box-shadow on image ) or we leave it as it is.
Personally, I would choose to leave it alone.

**Comment by selul** [comment]
we can leave it alone in this case.
