### ISSUE TITLE
[Post Type Grid] Meta size not working corectly

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#393]
The `size` control for `meta` does not increase the font size of the text, as it's selecting the correct element ( it selects its parent )
![Screenshot (2)](https://user-images.githubusercontent.com/3266155/68298392-ea5e3a80-00a1-11ea-952c-22bc1d43b66d.png)

Source: https://www.notion.so/themeisle/19423b64733743389c90461fe9893ceb?v=c62fbb45fc9c4746b2e4671d6b6ceeb4&p=09842fb54af544629ce1e810c277978c

**Comment by cristian-ungureanu** [comment]
this was fixed in Codeinwp/elementor-extra-widgets ... a new release for obfx should trigger the update

**Comment by rodica-andronache** [comment]
hi! can you share the archive with me so I can test?
