### ISSUE TITLE
Notices when using all Woo widgets from OBFX

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#397]
When using **OBFX's woo widgets**, like Woo Best Selling Products or Woo On Sale Products for example, multiple notices of this form appear:

Notice: Undefined index: before_widget in /Users/rodica/Local Sites/wordpress/app/public/wp-content/plugins/themeisle-companion/vendor/codeinwp/elementor-extra-widgets/widgets/woo/best-products.php on line 77
Notice: Undefined index: after_widget in /Users/rodica/Local Sites/wordpress/app/public/wp-content/plugins/themeisle-companion/vendor/codeinwp/elementor-extra-widgets/widgets/woo/best-products.php on line 93

![Screenshot](https://user-images.githubusercontent.com/3266155/69257327-908e6200-0bc3-11ea-8dc0-1169f921a928.png)

Source: https://wordpress.org/support/topic/php-notice-undefined-index-before_widget/

**Comment by cristian-ungureanu** [comment]
This was fixed in the composer module in this PR. https://github.com/Codeinwp/elementor-extra-widgets/pull/17 .Will be visible in the next release of OBFX

**Comment by rodica-andronache** [comment]
@cristian-ungureanu when you're done with the changes for OBFX, please share the archive with me, so I can test it. Thanks

**Comment by rodica-andronache** [comment]
@cristian-ungureanu I didn't get those notices anymore but saw others. Didn't test with all the widgets, but it looks to be the same one for all of them:
 
Notice: Undefined index: widget_id in /Users/rodica/Local Sites/wordpress/app/public/wp-content/plugins/themeisle-companion/vendor/codeinwp/elementor-extra-widgets/widgets/woo/recent-products.php on line 106

Notice: Undefined index: widget_id in /Users/rodica/Local Sites/wordpress/app/public/wp-content/plugins/themeisle-companion/vendor/codeinwp/elementor-extra-widgets/widgets/woo/popular-products.php on line 108

Notice: Undefined index: widget_id in /Users/rodica/Local Sites/wordpress/app/public/wp-content/plugins/themeisle-companion/vendor/codeinwp/elementor-extra-widgets/widgets/woo/sale-products.php on line 106
