### ISSUE TITLE
Notice using the Services widget

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#400]
How to replicate:
- create a post in Elementor
- add the Services widget from OBFX
- for one of the Services add a link in the Link to field
- a warning will appear on the frontend
![download](https://user-images.githubusercontent.com/3266155/69868008-3a9b7780-12b1-11ea-9f46-c7e6ae677f74.png)
![download (1)](https://user-images.githubusercontent.com/3266155/69868021-438c4900-12b1-11ea-9a05-42e4dad38eec.png)

**Comment by cristian-ungureanu** [comment]
@rodica-andronache  the problem was fixed here: https://github.com/Codeinwp/elementor-extra-widgets/pull/20 and it should go live after a new release for obfx.
