### ISSUE TITLE
[Social Sharing Module] Add YouTube as an option

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/themeisle-companion#401]
Someone wanted to use YouTube as an option for the Social Sharing Module from OBFX.

Even though YT is not a social platform like Facebook and it's more like a content creation platform, I think we can still consider adding it as an option for the module.

**Comment by cristian-ungureanu** [comment]
It's a sharing module. How do you share on yt? The client probably needs a
button with a link to yt.

**Comment by SilviuDinu** [comment]
@cristian-ungureanu I agree with you. As I said, YT is more likely a content creation platform and you're right, a button with a link for yt would be as good as any. 

However, YT has introduced some kind of posting system like this -> https://prnt.sc/q49589 where you can share stuff.

Anyway, the user specifically asked this scenario to happen within the OBFX module, even after I explained how YT is not used for sharing things like Facebook. And given the fact that YT has now a posts system where you can drop likes and comments, I think it would be possible.

I will keep an eye out for more requests like this and let you know .
