### ISSUE TITLE
No permission to hide the activation notice (or view dashboard)

### ISSUE THREAD

**Issue by patrickvdlinden** [Codeinwp/themeisle-companion#404]
Ref: https://github.com/Codeinwp/themeisle-companion/blob/cab05fc61c0039c4a5bf1b0d7d7539b4ebc13a33/core/app/class-orbit-fox-admin.php#L137

The activation notice within the dashboard has a close button, but when logged in as a _non_-administrator this goes to a permission denied page (/wp-admin/admin.php?page=obfx_companion&obfx_ignore_visit_dashboard_notice=0) and it stays visible afterwards.
The link to the dashboard within the notice is also going to the same permission denied page.

**Comment by rodica-andronache** [comment]
+1 https://twitter.com/allanaaaaaaa/status/1232769618453958658

**Comment by selul** [comment]
should be fixed in the latest release.
