### ISSUE TITLE
Contact form broke layout in Beaver Builder

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#413]
I'm not sure what may have caused this, but I just noticed some of the Beaver Builder starter sites have the Contact Form layout messed up on the frontend. In the backend, it looks good from what I've seen.

![Screenshot (4)](https://user-images.githubusercontent.com/3266155/73854890-e924e100-483b-11ea-949b-453aba237c78.png)

Some examples
https://demo.themeisle.com/neve-wedding-bb/neve-wedding-bb-contact/
https://demo.themeisle.com/neve-rokophoto-bb/neve-rokophoto-bb-contact/
https://demo.themeisle.com/neve-real-estate-bb/neve-real-estate-bb-contact/
https://demo.themeisle.com/neve-video-agency-bb/neve-video-agency-bb-contact-us/

**Comment by selul** [comment]
should be fine now.
