### ISSUE TITLE
Warning on Frontend regarding Gutenberg Blocks

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/themeisle-companion#414]
Someone reported a warning appearing on the Frontend while having both OrbitFox and Otter updated on the latest version. 

The warning appears on all pages except the frontpage and it looks like this:

> Warning: Use of undefined constant THEMEISLE_BLOCKS_VERSION - assumed 'THEMEISLE_BLOCKS_VERSION' (this will throw an Error in a future version of PHP) in /customers/d/f/b/hulemaendihabitter.dk/httpd.www/wp-content/plugins/themeisle-companion/vendor/codeinwp/gutenberg-blocks/inc/css/class-block-frontend.php on line 146

I was also been able to replicate some sort of issue on my local and it looks like this -> https://prnt.sc/qzaobx
The issue occurred for me after I added a section template with Otter (cc @HardeepAsrani)

Please let me know if you require more details.

It looks like defining the version again fixes the issue -> 
![image](https://user-images.githubusercontent.com/33000230/74081901-9d04b700-4a5c-11ea-808e-dcb96c26c5ea.png)

**Comment by HardeepAsrani** [comment]
@selul would know more about this as he dealt with this issue.

**Comment by HardeepAsrani** [comment]
You can ask the person to deactivate Gutenberg Blocks module in Orbit Fox for now. We will see about the issue. @SilviuDinu

**Comment by selul** [comment]
@SilviuDinu your screenshot was wrong, it was not the good line/file, however I have fixed it and will include it in the next release.

**Comment by SilviuDinu** [comment]
@selul sorry about the screenshot. I followed the same path and line as described in the warning message. I thought it was the correct one.
