### ISSUE TITLE
Unable to integrate Google Analytics

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/themeisle-companion#422]
Steps Taken to replicate the issue:
From the **WP Dashboard** > **Orbit Fox**.
Enabled the **Analytics Integration**.
At the bottom of the same page, there would be a green button available says '**Authenticate with Google**'. See here -->> https://snipboard.io/hQiDu4.jpg
Clicked on the green button and chose a Google account.
Got an error "S**ign in with Google is temporarily disabled for this app**".
See here -->> https://snipboard.io/RxwHDi.jpg

Ticket: https://secure.helpscout.net/conversation/1093296204/218117/

**Comment by abaicus** [comment]
@purplecodes Google has approved our Application, so everything should be good now :+1:

**Comment by rodica-andronache** [comment]
After selecting the Google account, I got these notices
`Notice: Trying to get property 'tracking_code' of non-object in /Users/rodica/Local Sites/wp5/app/public/wp-content/plugins/themeisle-companion/obfx_modules/google-analytics/init.php on line 254`
![Screenshot (1)](https://user-images.githubusercontent.com/3266155/77309680-be1c2100-6d05-11ea-89a8-7cf87dc0eacd.png)
