### ISSUE TITLE
Feature: hidden field in contact form

### ISSUE THREAD

**Issue by NicoPL** [Codeinwp/themeisle-companion#446]
As firstly specified in #147, hidden fields in the contact form would be very helpful.
If we use several contact forms for several usages, it's not possible when we get the email to know what was the purpose. Having hidden fields would provide more information when receiving the email and be able to segregate the demands.

Exemple, if we have on a same page:
- "contact form" used to subscribe to a service
- "contact form" used for suggestions
- "contact form" used for asking for information

Other example, with only an "email" field and "send" button to
- request for information
- subscribe to a newsletter
- be part of a betatester group
- subscribe to an event

**Comment by cristian-ungureanu** [comment]
@rodica-andronache I've added an option to make a field hidden. When you have some time please have a look at [this PR](https://github.com/Codeinwp/themeisle-content-forms/pull/49).

**Comment by NicoPL** [comment]
Sounds great thank you

**Comment by rodica-andronache** [comment]
@cristian-ungureanu it's working well.
There's just a small thing, visible when you add the Hidden field somewhere in the middle of the form, and use certain themes, like Twenty Twenty for example. 
The spacing option applies to the hidden input as well, leaving a white space there.
<img width="1654" alt="Screenshot 2020-04-21 at 12 49 07" src="https://user-images.githubusercontent.com/3266155/79854817-b5853c00-83d2-11ea-9060-042c5a4cd441.png">

Apart from that, when using the `{current_url}` magic tag on this page http://rodicaelena.com/elementor-2789/ for example, I got  http://rodicaelena.com/wp-json/content-forms/v1/submit. Is that correct? I was expecting http://rodicaelena.com/elementor-2789/

**Comment by cristian-ungureanu** [comment]
@rodica-andronache fixed both issues, it should work now. Thanks for testing!

**Comment by rodica-andronache** [comment]
@cristian-ungureanu it's working well.
Another small thing. I think we should have the `Field Width` option visible for Hidden fields as well because right now it works like this:
I click on Add a new field. At this point, the default for Field Width is 25%. 
When I select Hidden field, the Field Width option disappears, but the field will actually use that 25% value.
And this is causing the Submit form to not align well in some cases, and it's difficult to understand where that is coming from
![Screenshot (4)](https://user-images.githubusercontent.com/3266155/79869928-cf327d80-83ea-11ea-835e-3ee3f3411750.png)

**Comment by cristian-ungureanu** [comment]
@rodica-andronache the hidden field wrapper has display: none; so it shouldn't affect the form alignment and it shouldn't matter what width is there. I tried to put it with a width of 25% and make it the first one. The second and third fields have 50% and it looks normal. Do you have a specific configuration of the form when it's not looking as it should? I tried it in Hestia and in Twenty Twenty with Beaver Builder.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu I've tried it using Beaver with Neve and the hidden field being the last one in the form. 
In that case, the hidden field was 25% by default, and the submit button wasn't aligned anymore
https://www.loom.com/share/bfdc2b4969014253abac52e2fd507cfa

**Comment by cristian-ungureanu** [comment]
@rodica-andronache I don't think you've got the latest version from here https://github.com/Codeinwp/themeisle-content-forms/pull/49. In [this commit](https://github.com/Codeinwp/themeisle-content-forms/pull/49/commits/5e071eb5a345042bcaf2f9bd15a742a4f2d84c99), I've added "display:none" to that file. I also tested on neve and it's working well. It's either the cache or you don't have the latest changes.

**Comment by rodica-andronache** [comment]
it was cache, sorry
