### ISSUE TITLE
Don't localize module IDs

### ISSUE THREAD

**Issue by oriolarcas** [Codeinwp/themeisle-companion#465]
Hi,

I reported this 1 year ago in [WP support](https://wordpress.org/support/topic/fixed-bug-in-localized-sites/) but it didn't go through, so I'll try here.

The modules are constructed like [this](https://github.com/Codeinwp/themeisle-companion/blob/v2.9.8/obfx_modules/menu-icons/init.php#L33):

```php
<?php
$this->name = __( 'Menu Icons', 'themeisle-companion' );
?>
```

Note that the `name` is **localized**.

Then the base class enqueues JS scripts like [this](https://github.com/Codeinwp/themeisle-companion/blob/v2.9.8/core/app/abstract/class-orbit-fox-module-abstract.php#L560):

```php
<?php
$sanitized = str_replace( ' ', '-', strtolower( $this->name ) );
...
$id = 'obfx-module-' . $prefix . '-js-' . $sanitized . '-' . $order;
...
if ( array_key_exists( $file_name, $this->localized ) ) {
	wp_localize_script(
		$id,
		str_replace( '-', '_', $sanitized ),
		$this->localized[ $file_name ]
	);
}
?>
```

Note that the `name` from the module class, which was localized, is used to generate JS code.

In localized setups, this generates invalid JS like this:

```javascript
<script>
var iconos_de_menú = {"icons":["dashicons-menu", ...
</script>
```

Note the invalid, localized JS variable. This causes a JS error in the `Appearance > Menus` admin page:

```
ReferenceError: menu_icons is not defined
```

Because `menu-icons` is expected, but `iconos_de_menú` is generated.

I think it is a bad practice to use `$this->name` both as a localized string to display messages to the user, and to generate JS code, in general.

I suggest using two variables for that, one for the module ID and one for the module name, in all the modules.

Thanks.

**Comment by oriolarcas** [comment]
Sorry to bump this, but I'm unable to update this plugin until you fix this bug.

**Comment by cristian-ungureanu** [comment]
Hi @oriolarcas. Thanks for letting us know. We apologize that this took so long to be fixed.
The fix will be in the next version so you should be able to update now without problems.
