### ISSUE TITLE
Newsletter Form: Double opt in is still working even if disabled.

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/themeisle-companion#479]
Using the Newsletter form widget, selecting Mailchimp as the provider.
There is an option inside Mailchimp to disable the double opt in. 
The setting can be found under Audience >  View Contacts > Settings > Audience Name and Defaults
https://snipboard.io/ByiCVt.jpg

When the enable double opt in is unchecked, I still get an email (as a subscriber) to confirm the subscription. 

I tested this with Elementor Pro's Form widget and it works as single opt in as intended.
I don't get the notification email and I'm automatically subscribed.

Ticket: https://wordpress.org/support/topic/newsletter-how-to-disable-double-opt-in/#post-12976731

**Comment by cristian-ungureanu** [comment]
This issue was fixed here https://github.com/Codeinwp/themeisle-content-forms/pull/51, after the merge and a new release for OBFX it should take in count the double opt-in option from MailChimp.

**Comment by rodica-andronache** [comment]
- [ ] hidden type input not available anymore

<img width="554" alt="Screenshot 2020-07-09 at 16 44 49" src="https://user-images.githubusercontent.com/3266155/87047822-a8266380-c203-11ea-8e20-1d7fd60949b4.png">
<img width="453" alt="Screenshot 2020-07-09 at 16 45 08" src="https://user-images.githubusercontent.com/3266155/87047831-ab215400-c203-11ea-8b89-f4b0fc556f37.png">

- [ ] I think that for checkbox, the Placeholder option should not exist, as is not used anywhere https://prnt.sc/terg7t

- [ ] The Hide Label option doesn't make sense to apply to the checkbox https://prnt.sc/terip7

**Comment by rodica-andronache** [comment]
@cristian-ungureanu I've tested the issue with the double opt-in in Mailchimp and its working well.
These are few things I've saw related to the new checkbox type field you've added:
- [ ] the `hidden` type input is not available anymore in this PR compared to production

<img width="554" alt="Screenshot 2020-07-09 at 16 44 49" src="https://user-images.githubusercontent.com/3266155/87047822-a8266380-c203-11ea-8e20-1d7fd60949b4.png">
<img width="453" alt="Screenshot 2020-07-09 at 16 45 08" src="https://user-images.githubusercontent.com/3266155/87047831-ab215400-c203-11ea-8b89-f4b0fc556f37.png">

- [ ] I think that for checkbox, the `Placeholder` option should not exist, as is not used anywhere https://prnt.sc/terg7t

- [ ] The `Hide Label` option doesn't make sense to apply to the checkbox https://prnt.sc/terip7 -> this is happening just in Elementor, in Beaver is ok

- [ ] the new checkbox type field appears in the Newsletter widget too. Is that ok?

- [ ] there are also conflicts here https://github.com/Codeinwp/themeisle-content-forms/pull/51

**Comment by cristian-ungureanu** [comment]
@rodica-andronache the problem was that the dev branch was behind the master. Here's the fix for MailChimp https://github.com/Codeinwp/themeisle-content-forms/pull/53.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu thanks. can you also please the conflicts here? https://github.com/Codeinwp/themeisle-content-forms/pull/53

**Comment by cristian-ungureanu** [comment]
@rodica-andronache done
