### ISSUE TITLE
Recommended plugins can't be installed

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#500]
In `OrbitFox > General Settings` we have a `Recommended Plugins` tab where we list a few plugins including Optimole.
But none of the plugins can't be installed. Clicking on the `Install now` button from the popup doesn't do anything.
![c](https://user-images.githubusercontent.com/3266155/88193185-090f5c00-cc46-11ea-8c3a-0079f645b3ec.png)
![cc](https://user-images.githubusercontent.com/3266155/88193200-0d3b7980-cc46-11ea-8e8c-928ce98c1fa6.png)

**Comment by cristian-ungureanu** [comment]
@selul I can't find a solution here. I've searched a bit and it seems this happens since wp 4.6 ... I found a similar issue here https://github.com/TGMPA/TGM-Plugin-Activation/issues/649 but I have no clue why it isn't working because it's just a link. Maybe a prevent default somewhere.

**Comment by cristian-ungureanu** [comment]
@rodica-andronache the issue was fixed here https://github.com/Codeinwp/themeisle-companion/pull/520. I removed the popup as Marius suggested on slack a while ago.
