### ISSUE TITLE
Menu icons in when used in Mega Menu creates a bigger space

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/themeisle-companion#501]
Not really a bug but when enabling the menu icons module in Orbit Fox and used it in a mega menu, the space between the icon and the menu item is quite noticeable.

Regular Menu
![2020-07-23_18h58_32](https://user-images.githubusercontent.com/32997072/88282707-a4730080-cd1c-11ea-859a-5700e4a81003.png)

Mega Menu 
![2020-07-23_19h27_17](https://user-images.githubusercontent.com/32997072/88282749-b3f24980-cd1c-11ea-9faf-64f7bad9e213.png)

Ticket:
https://wordpress.org/support/topic/orbit-fox-icon-for-mega-menu-item-creates-alignment-issues/#post-13160122

**Comment by abaicus** [comment]
Handled in [this PR](https://github.com/Codeinwp/neve/pull/1848) with [this commit](https://github.com/Codeinwp/neve/pull/1848/commits/0836dd2f74e9e9bcaddd68105619fb089e2da55b).
