### ISSUE TITLE
Notices when using Elementor

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#525]
Install both OBFX and Elementor, and try to edit/add a new page/post. In some cases, this notice appears.
<img width="651" alt="obfx-error" src="https://user-images.githubusercontent.com/3266155/90730942-a4d9c980-e2d1-11ea-9fe6-ce9cf5e18bcb.png">

**Comment by selul** [comment]
we should review the whole codebase for `register_rest_route` and see where is correctly used or not, including vendor folder.

**Comment by cristian-ungureanu** [comment]
The issue was fixed in https://github.com/Codeinwp/themeisle-content-forms/pull/55. I also checked Obfx and all vendors and every rest route is registered correctly.
