### ISSUE TITLE
Icons from Obfx Elementor widgets aren't visible on front-end

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/themeisle-companion#526]
When i add a obfx widget with elementor (Services or Pricing Table), the icons present in the widget aren't visible on front-end **until i change one of them.**
This happens with any theme used.
https://www.loom.com/share/437680a6340c45848681039e91119079

**Comment by cristian-ungureanu** [comment]
@irinelenache I could not replicate this issue. Tried it on Jurassic Ninja and on my local instance. I also tried enabling Font Awesome 4 support in Elementor's settings. Here are my settings https://prnt.sc/ui25ga.

https://www.loom.com/share/873955ed44234155ad622fb285d72e1b

Can you test again and let me know if it still happens?

**Comment by irinelenache** [comment]
@cristian-ungureanu i tested it again on a new wp instance and found this only happens when **Otter blocks plugin is activated**.
If i deactivate it and refresh the page, the icons are visible again.
https://www.loom.com/share/c50550d6624a4561a77a5bb87b1e97ec

**Comment by cristian-ungureanu** [comment]
@irinelenache I managed to replicate the problem, thanks.

The issue is fixed here https://github.com/Codeinwp/elementor-extra-widgets and it will be visible when we make a new release of Obfx.

**Comment by irinelenache** [comment]
Tested it and now it works fine :+1:
