### ISSUE TITLE
Unable to add custom fonts 

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/themeisle-companion#574]
Following the documentation below to add the custom fonts:
https://docs.themeisle.com/article/1311-custom-fonts-orbit-fox-module

Issue: Unable to add custom fonts. Error: Sorry, this file type is not permitted for security reasons.
https://snipboard.io/j7v3hS.jpg

Steps to replicate the issue:
1. After enabling the Custom Fonts module, go to Appearance > Custom Fonts.
2. Upload the .ttf file -->> https://snipboard.io/w5OXqB.jpg
3. That is when the error comes up -->> https://snipboard.io/j7v3hS.jpg

**Comment by cristian-ungureanu** [comment]
@purplecodes thanks for reporting it.
A quick solution would be to install a plugin that allows you to whitelist certain fille types. Please have a look at this plugin https://wordpress.org/plugins/wp-add-mime-types/.

Another solution is to add this piece of code in the plugin:
```
    add_filter('upload_mimes', 'add_custom_upload_mimes');
    function add_custom_upload_mimes($existing_mimes) {
        $existing_mimes['ttf'] = 'application/x-font-ttf';
        return $existing_mimes;
   }
```

@selul what do you think. Should we add it in obfx or just recommend that plugin?

**Comment by selul** [comment]
yes, we should have it in obfx

**Comment by cristian-ungureanu** [comment]
@purplecodes is this a HS ticket? I tried to upload .ttf files and everything works, there's no need to add anything. There might be some compatibility issues with some plugin, or maybe the server is restricting that type of file. I tried on jurassic ninja and a couple of other live sites and everything looks ok.

**Comment by purplecodes** [comment]
@cristian-ungureanu thanks for checking. Here is the ticket for reference:
https://secure.helpscout.net/conversation/1341467558/253573/

I created a jurassic ninja account and still got an error.
https://slippery-bird.jurassic.ninja/wp-admin/
UN and PW:   demo2

Here is the ttf file I used for testing:
https://www.dropbox.com/s/0f808ih7068x44l/BAHNSCHRIFT.TTF?dl=0

**Comment by cristian-ungureanu** [comment]
@purplecodes the problem is the file. Its extension is TTF instead of ttf (lowercase). I've changed it and I managed to upload the file.

**Comment by purplecodes** [comment]
@cristian-ungureanu I was able to upload it using .ttf. Will advise the customer and update the docs as well.
