### ISSUE TITLE
Orbit fox messing with Jetpack screen

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/themeisle-companion#59]
Jetpack's Dashboard shrinks once you activate Orbit Fox.

Before: https://s.nimbus.everhelper.me/share/1094052/rs9qadxi7k2x1o84vuwl

After: https://s.nimbus.everhelper.me/share/1094053/fzimgn4frxk23ekk7kxy

**Comment by Firestorm-Graphics** [comment]
+1 can confirm that too

**Comment by ineagu** [comment]
we need to make sure that we don't load scripts where thye aren't needed. cc @preda-bogdan

**Comment by selul** [comment]
@preda-bogdan we need to load the admin assets just on pages where are needed.
