### ISSUE TITLE
Translating navigation within Post Type Grid doesn't work

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/themeisle-companion#622]
When using the **Post Type Grid** widget on a page edited with Elementor, the navigation can't be translated.

![post-grid-translate-issue](https://user-images.githubusercontent.com/26867648/106146037-e1fa8f80-617e-11eb-98d7-d0f6b68b13a9.png)

The issue might occur due to the textdomain being hardcoded in **vendor/codeinwp/elementor-extra-widgets/widgets/elementor/posts-grid.php**

![post-grid-issue-cause](https://user-images.githubusercontent.com/26867648/106146315-343bb080-617f-11eb-8f4b-4899947a99b9.png)

Orbit Fox version: 2.10.3
Elementor version: 3.1.0
WordPress version: 5.6

ticket: https://secure.helpscout.net/conversation/1407063762/263452/

**Comment by cristian-ungureanu** [comment]
@stefan-cotitosu the issue should be fixed in the latest release. Don't forget to notify our client. Thanks for reporting this! 🚀
