### ISSUE TITLE
Elementor blocks throw errors in console when added

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/themeisle-companion#700]
When i add obfx blocks to an elementor page, i get some errors in the console and if i edit the block, the changes take effect only in front-end.
https://vertis.d.pr/74hO8s

**Obfx version:** 2.10.6
**Elementor version:** 3.2.5
**Wordpress version:** 5.7.2 / 5.8 RC1

**Comment by cristian-ungureanu** [comment]
@irinelenache the issues were from the composer packages that we have ( elementor-extra-widgets and themeisle-content-forms ).
To test the fixes for this, grab the development branch from this repo and run in the terminal "yarn install", "composer install", "yarn run build".
The errors were from widgets that had in their settings some repeaters ( the forms widgets, the pricing table, and the services widget ). Make sure you add those and check the console after.

**Comment by irinelenache** [comment]
@cristian-ungureanu The elementor widgets are fixed now 👍
