### ISSUE TITLE
Removing Otter Blocks from Orbit Fox

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/themeisle-companion#702]
The idea is to first disable the module for new installs while allowing old installs some time to migrate to Otter plugin itself. And then removing the package altogether.

**Comment by selul** [comment]
I think we can also disable if Otter is present, if we don't do this already.

**Comment by selul** [comment]
@cristian-ungureanu please validate the PR with @HardeepAsrani too

**Comment by cristian-ungureanu** [comment]
@selul @HardeepAsrani 

Here's what I did here:
1. The module does not appear if Otter is active or if the current user is new.
2. If the module appears:
    - I added a notice under the module description saying that the module will soon be removed: https://vertis.d.pr/Ky9mKR
    - I added a dismissible notice that is saying you should install Otter: https://vertis.d.pr/J4o8GT.
    - I added Otter at recommended plugins and when you dismiss the notice, it will redirect you to recommended plugins: https://vertis.d.pr/T1LGWT

I made a PR here: https://github.com/Codeinwp/themeisle-companion/pull/703

**Comment by selul** [comment]
A few things I saw: 

1. If the module is switched off, we should remove it from the list, preventing the users from enabling it. 
2. Notice should be present on the OrbitFox page, not all around the admin.  

@HardeepAsrani let me know your thoughts too on this and if you see any other changes

**Comment by HardeepAsrani** [comment]
Looks good, same as Marius said about removing it from the list and making the notice only in Orbit Fox screen.
