### ISSUE TITLE
retire analytics and monitor modules

### ISSUE THREAD

**Issue by selul** [Codeinwp/themeisle-companion#704]
Since we lack any grand plan for those two modules I thought that is better to retire them directly. 

- For the monitoring module, let's remove the module code completely and add a notice when going to OrbitFox admin page in case that they had any monitoring active for that site saying: 
`We have retired the free uptime monitoring module in OrbitFox since we haven't been able to dedicate more time into its development and direction. We recommend instead using services like uptimerobot.com, cronitor.io, or updown.io instead which provide more options/integrations and faster checks.`

The notice can be hidden once it's shown once. 

- For the analytics module, let's remove the connection to the analytics service, keep the saved data and allow the user only to select from the locally saved codes. The refresh button can be also removed. If they haven't connected with the analytics service we can remove the module from the list entierily.

**Comment by irinelenache** [comment]
@cristian-ungureanu tested with the `remove-modules` branch and it works fine for me 👍
