### ISSUE TITLE
Update OrbitFox description, screenshots and banner

### ISSUE THREAD

**Issue by cristian-ungureanu** [Codeinwp/themeisle-companion#706]
We have 3 retired modules, Gutenberg Blocks, Uptime monitor, and the Analytics module. We need to update the description and the visuals ( banner and screenshots if needed ) on https://wordpress.org/plugins/themeisle-companion/.

We need to remove any occurrences of those modules.

@mghenciu, can you help me with the visuals, please?

**Comment by mghenciu** [comment]
@cristian-ungureanu, I updated the banner by removing mentioned Modules:
https://www.figma.com/file/Ma7IPJwPUMlEUrWd5oWonP/OrbitFox?node-id=582%3A94
![image](https://user-images.githubusercontent.com/52494172/128033984-d75e4b6d-5f25-410e-94ac-ee282d0f8243.png)


In case there are other design things, that need to be changed while I am gone, you can ask Andreea Tae.

**Comment by cristian-ungureanu** [comment]
I managed to update the banner with Mihai's help 🍻. I also updated the description, removed any mentions of the retired modules, and added some mentions about the newly added modules, custom fonts, and header footer scripts.
