### ISSUE TITLE
Missing div tags from Pricing Table elements

### ISSUE THREAD

**Issue by ewminty-private** [Codeinwp/themeisle-companion#712]
Header fields render HTML classes as text because the div and /div tags are missing after updating to 2.10.7 (OK in 2.10.6)
Result is that existing pricing table elements do not render correctly and appear corrupted (cannot be edited) in Elementor.

Wordpress Version 5.8.1
Elementor Version 3.0.7
Elementor Pro Version 3.0.4
Orbit Fox Companion Version 2.10.7

Expected results:
```
<div class="obfx-pricing-table-title">Title Text</div>
<div class="obfx-pricing-table-subtitle">Subtitle Text</div>
```

Actual results:
`< class="obfx-pricing-table-title">Title Text< class="obfx-pricing-table-subtitle">Subtitle Text`

**Comment by cristian-ungureanu** [comment]
@ewminty-private I can't replicate it. I'm testing with both Obfx 2.10.7 and 2.10.8 and everything works as expected. If the problem persists, can you create a staging site on https://tastewp.com/ where you replicate the issue and share with us the credentials?

**Comment by cristian-ungureanu** [comment]
Closing this as it was not possible to replicate it and there were no other reports about this issue. Feel free to reply to this thread if you have more information about it.
