### ISSUE TITLE
remove template directory

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-companion#715]
@selul maybe is worth removing this : admin.php?page=obfx_template_dir, we can leave the sub-menu item and instead of template we can show something similar to what we have in neve, a background image + we recommend Neve for 100+ templates.

**Comment by cristian-ungureanu** [comment]
@arinaturcu I've started something here on the feat/remove-templates branch but I didn't have time to finish it. You can either continue there or start from scratch.
What I did here is that when the [Template directory module](https://vertis.d.pr/t9vXJd) is active, on the page where the previous templates were displayed, I've added this notice https://vertis.d.pr/FIKK37.
The notice needs an Install & Activate button for both Neve and Template clouds. When both are installed and active, the Template Directory page from here https://vertis.d.pr/ZqOtpu should point to the starter templates ( https://neve.test/wp-admin/themes.php?page=tiob-starter-sites )

**Comment by cristian-ungureanu** [comment]
@Codeinwp/design-team can you help us a bit with some design? The functionality works great but the design it's not that good https://vertis.d.pr/XQpk38

**Comment by mghenciu** [comment]
I did some exploration for this, and I think it's best not to display both buttons/notices at the same time.
But I tried an approach with both buttons (not polished), and as you can see, this may get confusing -> too many buttons, decisions to take, informations to read:
[Figma](https://www.figma.com/file/Ma7IPJwPUMlEUrWd5oWonP/OrbitFox?node-id=783%3A52)
![image](https://user-images.githubusercontent.com/52494172/148557849-a0845269-49f5-459c-9731-300514bc75ae.png)


## So I would recommend one of this 2 approaches (below)
### 1. Gradually show notices, from existing components
We already have a modal in TPC, when Neve is disabled. And I suggest to make this gradually, first show in OBFX Template Directory, the TPC install notice:
![image](https://user-images.githubusercontent.com/52494172/148564160-23d8d406-3c75-4806-ae9d-df9753a91564.png)
This way users can preview the available Starter Sites, without taking the 'big step to install Neve'.
<br>
And when the user tries to import a Starter Site, the existing modal about Neve will popup:
![image](https://user-images.githubusercontent.com/52494172/148565493-670910e1-5d09-488c-bbeb-203b159ae83b.png)

***

### 2. Use a stepped flow
This way we avoid the cognitive load, by having just one button.
And if TPC is Installed + Activated, the _admin.php?page=obfx_template_dir_ will be a redirect to Starter Sites page.
![image](https://user-images.githubusercontent.com/52494172/148561030-2aae6353-6607-4d73-a887-a0e3e0f9efa0.png)
![image](https://user-images.githubusercontent.com/52494172/148561166-e48f778e-b6dc-4125-8c1c-af056036b657.png)

**Comment by cristian-ungureanu** [comment]
Thank you @mghenciu.

@arinaturcu I think we can go with `2. Use a stepped flow`. If this is too complicated to achieve ( It will take you > 2h to implement ) we can get rid of the stepped part and just show the notices one by one in the same design that Mihai provided.

**Comment by cristian-ungureanu** [comment]
@arinaturcu I discovered an error in OrbitFox dashboard after merging this. It appears everywhere in the dashboard ( except the page where the notices appear ) when the template directory module is enabled.

https://vertis.d.pr/YMsFsM

My guess is that we load the js everywhere and it doesn't find the "obfx-template-directory" id.

**Comment by arinaturcu** [comment]
@cristian-ungureanu You are right, the js was loaded everywhere. I made a commit to fix the problem, hope everything is ok now.
