### ISSUE TITLE
Suggestion to add TasteWP link to the readme file so it appears in wordpress.org

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/themeisle-companion#732]
TasteWP contacted us with this suggestion:

> An URL like [tastewp.com/new?pre-installed-plugin-slug=themeisle-companion&redirect=admin.php%3Fpage%3Dobfx_companion&ni=true](https://tastewp.com/new?pre-installed-plugin-slug=themeisle-companion&redirect=admin.php%3Fpage%3Dobfx_companion&ni=true) spins up a new TasteWP instance with the Orbit Fox plugin already installed. This allows your potential users to play around with your plugin without any commitments. :)
> 
> You could place this link in your readme.txt so that it shows up like [here](https://monosnap.com/file/O7UsIK1004UEVVIYsVdvout9FZhSOm), that way users can check out your plugin(s) with just one click. It's free for both you as well as your users (and will stay free).

I think it's a good addition that at least doesn't hurt for the plugin to have and helps potential users to check the plugin quickly.

**Comment by ineagu** [comment]
we should always remind ourself that 99% of the people install plugins from wp-admin, this link won't have much use for us, more for them and seo.

Also if they change something we need again to go and update.

I think something like this can be done, if we spin up our own site based on jurassic ninja image

**Comment by Skystream96** [comment]
+1 https://secure.helpscout.net/conversation/1880032287/322612?folderId=212390

same suggestion only that this time is about plugins too.

**Comment by selul** [comment]
We wont add this for now.
