### ISSUE TITLE
Usage of outdated php-http/discovery package may break some sites running PHP 7.4 or higher

### ISSUE THREAD

**Issue by unfulvio-godaddy** [Codeinwp/themeisle-companion#747]
Hi there!

We ran into an issue with some sites running this plugin alongside others utilizing the same php-http/discovery package. 

Using composer dependencies is tricky in WordPress since there is no real dependency management and concurrent plugins loading similar libraries/packages will inevitably collide. 

An additional issue here is that this plugin is using the 2019 version (1.6.1) of said package as a dependency instead of the latest (1.14.2) from May of this year.  

I would recommend to use the latest version. See current changelog for the dependency here: https://github.com/php-http/discovery/blob/master/CHANGELOG.md. This also makes your plugin not really supporting PHP 7.4 or or PHP 8.0 since this dependency didn't add support for that until 1.9.x. 

Alternatively, wrapping the dependency in a namespace to avoid collisions could be also a solution, although it may require more work or testing (see for example: https://github.com/humbug/php-scoper or https://github.com/coenjacobs/mozart and similar libraries).

**Comment by Skystream96** [comment]
+1 https://secure.helpscout.net/conversation/1996958217/335356?folderId=212390

**Comment by selul** [comment]
it can be tested here @irinelenache https://github.com/Codeinwp/themeisle-companion/pull/762
