### ISSUE TITLE
Breaking Hestia client section

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/themeisle-companion#754]
Version 2.10.13 of this plugin breaks the Hestia client section. The images appear in their actual size, so the formatting of the section looks broken. 
Screenshots
version 2.10.12 >> https://vertis.d.pr/RMdYvP
version 2.10.13 >> https://vertis.d.pr/XVfH6u

**Comment by irinelenache** [comment]
@cristian-ungureanu Tested both PRs linked to this issue and it's fixed now 👍
