### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/themeisle-companion#766]
A user reported a syntax error in themeisle-companion/vendor/symfony/polyfill-php80/bootstrap.php starting with line 29: syntax error, unexpected ‘?’, expecting variable (T_VARIABLE). Removing the "?" that shouldn't be there starting with that line solves the error.

Reported [here](https://wordpress.org/support/topic/remaining-error-since-v2-10-18/).

**Comment by selul** [comment]
fixed in the most recent version.
