### ISSUE TITLE
themeisle-blocks/advanced-blocks not supported

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/themeisle-companion#767]
There are some users that report an issue if they update to version 2.10.17 or higher: "your website doesn't support the “themeisle-blocks/advanced-blocks”. You can edit it in HTML". This occurs for them with every version of Orbit Fox starting with 2.10.17. The users that reported this don't have Otter installed, but one of them mentioned that the issue disappears if he installs it. Also, the issue disappears if they rollback to version 2.10.16. The blocks that get this error can't be edited anymore, they are not displayed properly on the page and they can't be added on a page anymore. I couldn't replicate this behavior, but there are quite a few users who mentioned it.

Reported [here](https://wordpress.org/support/topic/themeisle-blocks-advanced-columns-broken-after-orbit-fox-update-version-2-10-17/), [here](https://wordpress.org/support/topic/themeisle-blocks-block-is-not-supported-by-website/) and [here](https://wordpress.org/support/topic/themeisle-blocks-advanced-columns-block-is-not-supported-by-website/).

**Comment by selul** [comment]
Hey @MarinescuLucia,

The blocks from OrbitFox are retired for more than 1 year and they are moved into Otter Blocks, see this https://github.com/Codeinwp/themeisle-companion/releases/tag/v2.10.7 and we have removed entirely the module last month.
