### ISSUE TITLE
research module creation

### ISSUE THREAD

**Issue by selul** [Codeinwp/themeisle-companion#77]
@contactashish13 i would like to do document yourself how the modules works in this plugin. 

Basically, each module is independent, like sub-plugins, and we will develop in the future various modules, depending what the users will need. 

the documentation is here: https://github.com/Codeinwp/themeisle-companion/blob/master/docs/MODULE.md

**Comment by contactashish13** [comment]
@selul I'll need some basics to start me off on each of these sub-modules. How do I test them?
