### ISSUE TITLE
Hestia Pro customizer is not loading with Orbit Fox Version 2.10.21 

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/themeisle-companion#770]
Hestia Pro customizer is not loading with Orbit Fox Version 2.10.21. If we rollback to the previous version of the plugin, the customizer loads fine. 

Console error >> https://vertis.d.pr/i/UynprT

Screencast: https://vertis.d.pr/v/GivE4p

HS Ticket: https://secure.helpscout.net/conversation/2082581580/346791?folderId=212385

The issue can be replicated with PHP versions: 8.0.22, 8.0.19 (I have checked with 8.0 and 7.4 but couldn't replicate the same behavior)

**Comment by cristian-ungureanu** [comment]
Closing this issue since we've made another release to fix it
