### ISSUE TITLE
Update the banner with removed features that are no longer in the plugin

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/themeisle-companion#779]
### Description

Not really a bug but we have a banner here - https://wordpress.org/plugins/themeisle-companion/
That still states some modules that we already retired since version [v2.10.7](https://github.com/Codeinwp/themeisle-companion/releases/tag/v2.10.7)

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/36594177/224824873-17dc7dd3-7589-440d-824e-39938e54b6eb.png">

Modules like uptime monitor, Analytics integration are no longer in the plugin.

### Step-by-step reproduction instructions

Visit - https://wordpress.org/plugins/themeisle-companion/

### Screenshots, screen recording, code snippet or Help Scout ticket

Reported here - https://wordpress.org/support/topic/orbit-fox-suggests-to-use-neve-when-neve-is-already-installed-as-a-child-theme/#post-16527765

### Is the issue you are reporting a regression

No

___
### [Figma](https://www.figma.com/file/Ma7IPJwPUMlEUrWd5oWonP/OrbitFox?node-id=1375-17&t=z9Ad40n6dNfBvGNd-11)

**Comment by selul** [comment]
also Template library and 10+templates

**Comment by mghenciu** [comment]
I've removed the Mentioned modules and updated with some of the other ones we have based on the latest Dashboard of OrbitFox:

![OBFX - Updated 2023](https://user-images.githubusercontent.com/52494172/225545016-1d0fe294-bcdd-453b-82f8-017e3f903a14.png)

___
### [Figma](https://www.figma.com/file/Ma7IPJwPUMlEUrWd5oWonP/OrbitFox?node-id=1375-17&t=z9Ad40n6dNfBvGNd-11)

**Comment by cristian-ungureanu** [comment]
@HardeepAsrani do you think we should also generate a banner ( 1544x500 ) and an icon ( 256x256) for retina displays ( as mentioned [here](https://developer.wordpress.org/plugins/wordpress-org/plugin-assets/#banner-filenames) ) or it's enough what we have?

**Comment by HardeepAsrani** [comment]
@cristian-ungureanu If it doesn't require extra work, then a retina banner/icon will be great to have too. The banner text doesn't look as sharp on my retina devices.
