### ISSUE TITLE
THEMEISLE_COMPANION_VERSION in Zerif and Rhea

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#78]
https://github.com/Codeinwp/themeisle-companion/blob/265c52d7a4521b1b1cdfa168e9927ddbca326d47/obfx_modules/companion-legacy/init.php#L221

I see THEMEISLE_COMPANION_VERSION is defined only for Hestia now, but we are using it in Zerif too (and Rhea). For example here https://github.com/Codeinwp/zerif-lite/blob/production/sections/our_focus.php#L41
Should I change it in Zerif or we'll change it here?
@selul

**Comment by selul** [comment]
@rodica-andronache yes, if is used there too, we should add for all 3 then.
