### ISSUE TITLE
Installing Recommended plugins does not work

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#780]
### Description

Installing Recommended plugins from the Orbit Fox dashboard does not work

### Step-by-step reproduction instructions

Go to Orbit Fox > General Settings > Recommended Plugins and try to install one of the recommended plugins. A "Something went wrong. Please try again." notice will appear.

If a plugin is already installed, activating it from here works well. Just the installation process does not work well.

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="700" alt="Screenshot on 2023-03-14 at 10-20-29" src="https://user-images.githubusercontent.com/3266155/224940414-115562d9-9b26-4391-b2e8-671afbe91299.png">

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
I've changed the document link in this PR https://github.com/Codeinwp/themeisle-companion/pull/782
New URL: https://docs.themeisle.com/article/1270-social-sharing-icons-orbit-fox-module
