### ISSUE TITLE
About page integration

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/themeisle-companion#798]
### What problem does this address?

As described on this issue we need to add code to OrbitFox that will show about us page via SDK - https://github.com/Codeinwp/themeisle-sdk/pull/178

No upgrade to Pro button is needed for this one of course as there is no pro version of the plugin.

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I implemented the about us page in the attached PR #801, please check with the build zip, and let me know if you need any changes.

Thanks

**Comment by rodica-andronache** [comment]
@girishpanchal30 everything's working well 👍
