### ISSUE TITLE
Template Directory link needs to be updated

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#803]
### Description

The link from Orbit Fox > Template Directory https://vertis.d.pr/i/forRLf needs to be updated, to correspond with the new Neve page location. https://vertis.d.pr/i/YFua2W

### Step-by-step reproduction instructions

The current link is `wp-admin/themes.php?page=tiob-starter-sites` and it should be updated to `wp-admin/admin.php?page=tiob-starter-sites`

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @rodica-andronache,

When I click the `Template Directory` menu it will open the `/wp-admin/admin.php?page=obfx_template_dir` page.
Ref: https://tinyurl.com/242w7ps8
Can you please more details or your test instance so I can replicate this issue?

Thanks

**Comment by rodica-andronache** [comment]
Hi @girishpanchal30 here's a screencast https://vertis.d.pr/v/hBxXLx
```
https://l-capuchin-tine.vertisite.cloud/wp-admin/
user: admin
pass: (EmgDHm%gYLpt#Z94Cn9S9Ju
```

**Comment by girishpanchal30** [comment]
@rodica-andronache Thank you for the sharing details, I've fixed the issue with the attached PR

**Comment by rodica-andronache** [comment]
@girishpanchal30 everything's working well 👍
