### ISSUE TITLE
Installing Neve and TPC from OrbitFox > Template Directory leads to wrong page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#813]
### Description

https://vertis.d.pr/v/uQSw8i

### Step-by-step reproduction instructions

1. install OrbitFox
2. go to OrbitFox > Template Directory
3. click on Install & activate TPC
4. click on Install & activate Neve
=> you are redirected to a non-existing page

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
The link that is currently opened and doesn't work - https://screwwrench.s3-tastewp.com/wp-admin/themes.php?page=tiob-starter-sites

Correct link - https://screwwrench.s3-tastewp.com/wp-admin/admin.php?page=tiob-starter-sites

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the issue is fixed now, thank you 👍
