### ISSUE TITLE
Vulnerability issue

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/themeisle-companion#816]
### Description

A vulnerability issue was reported here - https://secure.helpscout.net/conversation/2451987456/396713?viewId=931544

### Step-by-step reproduction instructions

.

### Is the issue you are reporting a regression

No

**Comment by stefan-cotitosu** [comment]
I've asked the user who contacted us for the details of the vulnerability as they didn't share it yet. We'll come back with the details or I'll close the issue if we don't receive it. Apologies for the inconvenience.

**Comment by kushh23** [comment]
Hello there, 

They have replied and provided more details about the vulnerabilities in this ticket. Please check it out. Thank you!

https://secure.helpscout.net/conversation/2451987456/396713?folderId=931544

cc: @vytisbulkevicius

**Comment by vytisbulkevicius** [comment]
@preda-bogdan,

Please prioritize this tomorrow 🙏

**Comment by stefan-cotitosu** [comment]
Bogdan, I've added all the details [here](https://github.com/Codeinwp/themeisle/issues/1612). Thank you for helping us here.

**Comment by preda-bogdan** [comment]
I linked the PR, it should be resolved now, it's awaiting Code Review and then will be forwarded to testing.
