### ISSUE TITLE
Post Type Grid Elementor Widget Responsive Columns not working

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#870]
### Description

![Image](https://github.com/user-attachments/assets/24a9fa44-13fc-4972-81ba-fa827351f098)
![Image](https://github.com/user-attachments/assets/2a78b9dc-ae77-489d-bc49-e03475e4d491)

### Step-by-step reproduction instructions

1.  Create a page in Elementor
2. Add the Post Type Grid widget from OBFX
3. For Columns on mobile choose 1
4. Check the page on mobile -> More than one colum are displayed on mobile

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2765701520/441417?viewId=212385

### Is the issue you are reporting a regression

No

**Comment by calousy** [comment]
Post Type Grid is not anymore available for me in Elementor, starting with [2.10.40](https://github.com/Codeinwp/themeisle-companion/compare/v2.10.39...v2.10.40). Rollback to 2.10.39 and it's there!

**Comment by girishpanchal30** [comment]
@rodica-andronache I've reviewed this issue, and it seems all `Elementor` widget related problems have been resolved with this PR https://github.com/Codeinwp/themeisle-companion/pull/879.

![Image](https://github.com/user-attachments/assets/227cf5d4-16e1-4cca-91d8-768b53dca871)

cc @vytisbulkevicius 

Thanks

**Comment by girishpanchal30** [comment]
@rodica-andronache, I just updated the dropdown value and re-saved the settings. It seems to be working fine for me on your test instance as well.

![Image](https://github.com/user-attachments/assets/aa0cb6cb-5cf9-46f1-bd59-24a164e98ffb)
