### ISSUE TITLE
_load_textdomain_just_in_time for translations / i18n loaded too early

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#871]
### Description

The same issue as in Neve https://github.com/Codeinwp/neve/issues/4322

### Step-by-step reproduction instructions

1. Use WordPress 6.7
2. Set site language to something other than en_US
3. Ensure all translations are installed
4. Refresh site

### Screenshots, screen recording, code snippet or Help Scout ticket

![Image](https://github.com/user-attachments/assets/db3ba749-dba0-4f38-8185-3d3f2ba84a23)

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
I've reviewed this issue and fixed it here - https://github.com/Codeinwp/themeisle-companion/pull/872
