### ISSUE TITLE
Page builder widgets not appearing in Elementor anymore in latest update

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/themeisle-companion#878]
### Description

Page builder widgets not appearing in Elementor anymore in latest update. It worked well in 2.10.39
https://docs.themeisle.com/article/951-orbit-fox-documentation#page-builder-widgets

### Step-by-step reproduction instructions

1. Enable the page builder widgets in OBFX https://docs.themeisle.com/article/951-orbit-fox-documentation#page-builder-widgets
2. Create an Elementor page and search for the widgets -> the widgets are missing

### Screenshots, screen recording, code snippet or Help Scout ticket

![Image](https://github.com/user-attachments/assets/9cef47af-4208-4ae5-bc40-2bcf27506435)

https://wordpress.org/support/topic/2-10-41-missing-elementor-addons-and-widgets/

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by rodica-andronache** [comment]
+1 https://secure.helpscout.net/conversation/2774354589/442744?viewId=212385

**Comment by rodica-andronache** [comment]
+1 https://wordpress.org/support/topic/lastes-update-wiped-out-cards/

**Comment by girishpanchal30** [comment]
@rodica-andronache I've reviewed this issue and fixed it here - https://github.com/Codeinwp/themeisle-companion/pull/879

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2776514070/443397
