### ISSUE TITLE
Page builder widgets module incompatibility with Elementor 3.26 version

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/themeisle-companion#882]
### Description

With Elementor version 3.26 released today our OrbitFox module Page builder widgets is not working.
If you have module enabled:
<img width="1353" alt="Image" src="https://github.com/user-attachments/assets/ece1f8c1-4c35-4ad9-82b9-e5d36bb2489e" />

Elementor sidebar loads forever:
<img width="301" alt="Image" src="https://github.com/user-attachments/assets/f6ab1f56-70bc-4e30-881d-303de4ba79fa" />

Such error was reported:
`Uncaught Error: Class “Elementor\Core\Schemes\Typography” not found in /wp-content/plugins/themeisle-companion/vendor/codeinwp/elementor-extra-widgets/widgets/elementor/posts-grid.php
`

Reported: https://wordpress.org/support/topic/plug-in-broke-after-elementor-update/

### Step-by-step reproduction instructions

1. Install latest Elementor version 3.26 and Orbitfox
2. Enable Page builder widgets module
3. Load any page built with Elementor - sidebar won't finish loading

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
+1 https://secure.helpscout.net/conversation/2794934760/445961

**Comment by girishpanchal30** [comment]
@vytisbulkevicius I've reviewed the issue, and it appears to be related to the `elementor-extra-widgets` plugin.

I've resolved it with this [PR](https://github.com/Codeinwp/elementor-extra-widgets/pull/38
). Once you merge the PR, we'll need to update the [composer dependencies](https://github.com/Codeinwp/themeisle-companion/blob/master/composer.json#L35
) in `themeisle-companion` and release the update.

Thanks!
