### ISSUE TITLE
when hestia or zerif is active add a module for the enhancements

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/themeisle-companion#96]
@abaicus @selul I thought that the easiest thing for users to understand how orbitfox works is to have forntpagesections stuff as a module, so : 

if hestia is active add a module : hestia_enhancements and enable it by default, when disabled, users will loose those sections for frontpage.

would you find it helpful?

**Comment by abaicus** [comment]
@ineagu I think this could be helpful just have the same module with a different name based on the active theme.

**Comment by ineagu** [comment]
Or this

**Comment by selul** [comment]
i have added the changes.
